# Generated by Django 4.2.1 on 2023-08-10 10:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("contacts", "0008_alter_contactpage_assessment_trial"),
        ("addresses", "0002_address_created_address_modified"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="address",
            name="contact",
        ),
        migrations.RemoveField(
            model_name="address",
            name="is_primary",
        ),
        migrations.AddField(
            model_name="address",
            name="name",
            field=models.CharField(
                blank=True,
                help_text="Name but not required",
                max_length=255,
                verbose_name="Name",
            ),
        ),
        migrations.AlterField(
            model_name="address",
            name="city_town_village",
            field=models.CharField(
                help_text="required",
                max_length=255,
                verbose_name="city town or village",
            ),
        ),
        migrations.AlterField(
            model_name="address",
            name="line_one",
            field=models.CharField(
                help_text="Required", max_length=255, verbose_name="line one"
            ),
        ),
        migrations.AlterField(
            model_name="address",
            name="line_two",
            field=models.CharField(
                blank=True,
                help_text="Not required",
                max_length=255,
                verbose_name="line two",
            ),
        ),
        migrations.AlterField(
            model_name="address",
            name="postal_code",
            field=models.CharField(
                blank=True,
                help_text="Not required but preferable if available",
                max_length=100,
                verbose_name="post code or zip code",
            ),
        ),
        migrations.AlterField(
            model_name="address",
            name="prefecture_state",
            field=models.CharField(
                blank=True,
                help_text="Not required but preferable if available",
                max_length=100,
                verbose_name="prefecture or state",
            ),
        ),
        migrations.CreateModel(
            name="ContactAddress",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "contact_type",
                    models.CharField(max_length=20, verbose_name="Contact type"),
                ),
                (
                    "is_primary",
                    models.BooleanField(default=False, verbose_name="Is primary"),
                ),
                (
                    "address",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="addresses.address",
                    ),
                ),
                (
                    "contact",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="contacts.contact",
                    ),
                ),
            ],
        ),
    ]
