# Generated by Django 4.2.1 on 2023-08-11 09:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("addresses", "0005_alter_address_city_town_village_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contactaddress",
            name="contact_type",
            field=models.CharField(
                choices=[
                    ("HOM", "Home"),
                    ("WRK", "Work"),
                    ("HOF", "Head Office"),
                    ("BRO", "Branch Office"),
                ],
                default="HOM",
                max_length=3,
                verbose_name="Contact type",
            ),
        ),
    ]
