# Generated by Django 4.2.1 on 2023-11-07 09:11

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("addresses", "0008_experiencesaddress"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="ExperiencesAddress",
            new_name="ExperienceAddress",
        ),
    ]
