# Generated by Django 4.2.1 on 2023-11-07 09:20

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("addresses", "0009_rename_experiencesaddress_experienceaddress"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="experienceaddress",
            options={
                "verbose_name": "Experience Address",
                "verbose_name_plural": "Experience Addresses",
            },
        ),
    ]
