# Generated by Django 4.2.1 on 2023-07-26 09:23

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Contact",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    models.DateTimeField(auto_now_add=True, verbose_name="created"),
                ),
                (
                    "modified",
                    models.DateTimeField(auto_now=True, verbose_name="modified"),
                ),
                (
                    "name",
                    models.CharField(
                        blank=True,
                        help_text="Full name in the name order and language user would like. English or 日本語 for example. Max length: 100char",
                        max_length=100,
                        verbose_name="name",
                    ),
                ),
                (
                    "name_en",
                    models.CharField(
                        blank=True,
                        help_text="Full name in English, order should be same as name. Example 田中たろ should become Tanaka Taro in the field. Max length: 100char",
                        max_length=100,
                        verbose_name="english name",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
