# Generated by Django 4.2.1 on 2023-07-28 04:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("contacts", "0002_contact_primary_email_contact_user"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="contact",
            name="primary_email",
        ),
        migrations.AlterField(
            model_name="contact",
            name="user",
            field=models.OneToOneField(
                blank=True,
                help_text="Only connect this to user IF a site user exists. Make sure that the email used for the user is registered in Contact emails as primary. This will generally be done by the system but in case manual connection is required, you can in this interface",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.CreateModel(
            name="ContactEmail",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    models.DateTimeField(auto_now_add=True, verbose_name="created"),
                ),
                (
                    "modified",
                    models.DateTimeField(auto_now=True, verbose_name="modified"),
                ),
                (
                    "is_primary",
                    models.BooleanField(default=False, verbose_name="Is primary"),
                ),
                (
                    "email",
                    models.CharField(max_length=200, unique=True, verbose_name="Email"),
                ),
                (
                    "contact",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="contact_email",
                        to="contacts.contact",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
