# Generated by Django 4.2.1 on 2023-07-28 08:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("contacts", "0003_remove_contact_primary_email_alter_contact_user_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contactemail",
            name="contact",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="contact_emails",
                to="contacts.contact",
            ),
        ),
    ]
