# Generated by Django 4.2.1 on 2023-07-29 07:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("contacts", "0004_alter_contactemail_contact"),
    ]

    operations = [
        migrations.CreateModel(
            name="Notes",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    models.DateTimeField(auto_now_add=True, verbose_name="created"),
                ),
                (
                    "modified",
                    models.DateTimeField(auto_now=True, verbose_name="modified"),
                ),
                ("title", models.CharField(max_length=50, verbose_name="title")),
                (
                    "note_type",
                    models.IntegerField(
                        choices=[(0, "Regular"), (1, "Email")],
                        default=0,
                        verbose_name="note type",
                    ),
                ),
                ("note", models.TextField(verbose_name="note")),
                (
                    "contact",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="contact_notes",
                        to="contacts.contact",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
