# Generated by Django 4.2.1 on 2023-08-04 08:24

from django.db import migrations, models
import django.db.models.deletion
import streams.customblocks
import wagtail.blocks
import wagtail.fields
import wagtail_headless_preview.models


class Migration(migrations.Migration):
    dependencies = [
        ("wagtailcore", "0083_workflowcontenttype"),
        ("contacts", "0006_rename_notes_note"),
    ]

    operations = [
        migrations.CreateModel(
            name="ContactPage",
            fields=[
                (
                    "page_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="wagtailcore.page",
                    ),
                ),
                (
                    "ja_title",
                    models.CharField(
                        help_text="Required. Max length 15 characters.",
                        max_length=15,
                        verbose_name="Japanese Title",
                    ),
                ),
                (
                    "short_intro",
                    models.CharField(
                        help_text="A  oneline introduction of what this page is about. Max length 90 chars",
                        max_length=90,
                        verbose_name="Short Intro",
                    ),
                ),
                (
                    "assessment_trial",
                    wagtail.fields.StreamField(
                        [
                            ("rich_text", streams.customblocks.CustomRichTextBlock()),
                            (
                                "youtube",
                                wagtail.blocks.StructBlock(
                                    [
                                        (
                                            "src",
                                            wagtail.blocks.URLBlock(
                                                help_text="Get src from in the youtube embed code, include start if needed.",
                                                max_length=255,
                                                required=True,
                                            ),
                                        ),
                                        (
                                            "short",
                                            wagtail.blocks.BooleanBlock(
                                                help_text="Tick this box if the video is a short, i.e vertical format",
                                                required=False,
                                            ),
                                        ),
                                        (
                                            "limit",
                                            wagtail.blocks.BooleanBlock(
                                                help_text="Tick this box if you would like to limit recommended videos to this channel",
                                                required=False,
                                            ),
                                        ),
                                    ]
                                ),
                            ),
                            (
                                "q_and_a",
                                wagtail.blocks.StructBlock(
                                    [
                                        (
                                            "q_and_a_series",
                                            wagtail.blocks.ListBlock(
                                                wagtail.blocks.StructBlock(
                                                    [
                                                        (
                                                            "question",
                                                            wagtail.blocks.CharBlock(
                                                                help_text="Your question here. Max length 255",
                                                                max_length=255,
                                                                required=True,
                                                            ),
                                                        ),
                                                        (
                                                            "answer",
                                                            wagtail.blocks.TextBlock(
                                                                help_text="The answer to your question here.",
                                                                required=True,
                                                            ),
                                                        ),
                                                    ]
                                                )
                                            ),
                                        )
                                    ]
                                ),
                            ),
                        ],
                        null=True,
                        use_json_field=True,
                    ),
                ),
                (
                    "join_experience",
                    wagtail.fields.StreamField(
                        [
                            ("rich_text", streams.customblocks.CustomRichTextBlock()),
                            (
                                "youtube",
                                wagtail.blocks.StructBlock(
                                    [
                                        (
                                            "src",
                                            wagtail.blocks.URLBlock(
                                                help_text="Get src from in the youtube embed code, include start if needed.",
                                                max_length=255,
                                                required=True,
                                            ),
                                        ),
                                        (
                                            "short",
                                            wagtail.blocks.BooleanBlock(
                                                help_text="Tick this box if the video is a short, i.e vertical format",
                                                required=False,
                                            ),
                                        ),
                                        (
                                            "limit",
                                            wagtail.blocks.BooleanBlock(
                                                help_text="Tick this box if you would like to limit recommended videos to this channel",
                                                required=False,
                                            ),
                                        ),
                                    ]
                                ),
                            ),
                            (
                                "info_cards",
                                wagtail.blocks.StructBlock(
                                    [
                                        (
                                            "cards",
                                            wagtail.blocks.ListBlock(
                                                wagtail.blocks.StructBlock(
                                                    [
                                                        (
                                                            "title",
                                                            wagtail.blocks.CharBlock(
                                                                help_text="Title for card. Max length 20",
                                                                max_length=20,
                                                                required=True,
                                                            ),
                                                        ),
                                                        (
                                                            "image",
                                                            streams.customblocks.CustomImageChooserBlock(
                                                                help_text="Image size: 2048px x 1280px (16/10 ratio). Please optimize image size before uploading.",
                                                                required=True,
                                                            ),
                                                        ),
                                                        (
                                                            "text",
                                                            wagtail.blocks.TextBlock(
                                                                help_text="Text for card. Max length 100",
                                                                max_length=100,
                                                                required=True,
                                                            ),
                                                        ),
                                                    ]
                                                )
                                            ),
                                        )
                                    ]
                                ),
                            ),
                        ],
                        null=True,
                        use_json_field=True,
                    ),
                ),
                (
                    "question_and_answer",
                    wagtail.fields.StreamField(
                        [
                            (
                                "q_and_a",
                                wagtail.blocks.StructBlock(
                                    [
                                        (
                                            "q_and_a_series",
                                            wagtail.blocks.ListBlock(
                                                wagtail.blocks.StructBlock(
                                                    [
                                                        (
                                                            "question",
                                                            wagtail.blocks.CharBlock(
                                                                help_text="Your question here. Max length 255",
                                                                max_length=255,
                                                                required=True,
                                                            ),
                                                        ),
                                                        (
                                                            "answer",
                                                            wagtail.blocks.TextBlock(
                                                                help_text="The answer to your question here.",
                                                                required=True,
                                                            ),
                                                        ),
                                                    ]
                                                )
                                            ),
                                        )
                                    ]
                                ),
                            )
                        ],
                        null=True,
                        use_json_field=True,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
            bases=(wagtail_headless_preview.models.HeadlessMixin, "wagtailcore.page"),
        ),
    ]
