# Generated by Django 4.2.1 on 2023-08-11 14:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("contacts", "0009_contact_addresses"),
    ]

    operations = [
        migrations.AddField(
            model_name="contact",
            name="status",
            field=models.CharField(
                choices=[
                    ("LEA", "Lead"),
                    ("ACC", "Active Customer"),
                    ("INC", "Inactive Customer"),
                    ("BUP", "Business Partner"),
                ],
                default="LEA",
                help_text="Required",
                max_length=3,
                verbose_name="Status",
            ),
        ),
    ]
