# Generated by Django 4.2.1 on 2023-08-11 14:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("contacts", "0010_contact_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contact",
            name="status",
            field=models.PositiveSmallIntegerField(
                choices=[
                    (0, "Lead"),
                    (1, "Active Customer"),
                    (2, "Inactive Customer"),
                    (3, "Business Partner"),
                ],
                default=0,
                help_text="Required",
                verbose_name="Status",
            ),
        ),
    ]
