# Generated by Django 4.2.1 on 2023-08-12 03:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("contacts", "0011_alter_contact_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="contact",
            name="ind_or_org",
            field=models.PositiveSmallIntegerField(
                choices=[(0, "Individual"), (1, "Organization")],
                default=0,
                help_text="Required",
                verbose_name="Individual or Organization",
            ),
        ),
        migrations.AlterField(
            model_name="contact",
            name="status",
            field=models.PositiveSmallIntegerField(
                choices=[
                    (0, "Lead"),
                    (1, "Active Customer"),
                    (2, "Inactive Customer"),
                    (3, "Business Partner"),
                    (4, "Staff Member"),
                ],
                default=0,
                help_text="Required",
                verbose_name="Status",
            ),
        ),
    ]
