# Generated by Django 4.2.1 on 2023-08-12 04:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("contacts", "0013_contact_organization"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contact",
            name="organization",
            field=models.ForeignKey(
                blank=True,
                help_text="Not required",
                limit_choices_to={"ind_or_org": 1},
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="contacts.contact",
            ),
        ),
    ]
