# Generated by Django 4.2.1 on 2023-08-13 06:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("contacts", "0015_alter_contact_organization"),
    ]

    operations = [
        migrations.AddField(
            model_name="contact",
            name="gender",
            field=models.PositiveSmallIntegerField(
                choices=[
                    (0, "Male"),
                    (1, "Female"),
                    (2, "Other"),
                    (3, "Not Applicable"),
                ],
                default=3,
                help_text="Required",
                verbose_name="Gender",
            ),
        ),
    ]
