# Generated by Django 4.2.1 on 2023-08-13 10:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("contacts", "0016_contact_gender"),
    ]

    operations = [
        migrations.AddField(
            model_name="contact",
            name="child_of",
            field=models.ManyToManyField(
                blank=True,
                help_text="Not required",
                related_name="guardian_of",
                to="contacts.contact",
            ),
        ),
    ]
