# Generated by Django 4.2.1 on 2023-08-13 10:46

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("contacts", "0017_contact_child_of"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="contact",
            name="child_of",
        ),
    ]
