# Generated by Django 4.2.1 on 2023-10-05 13:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("contacts", "0020_alter_contact_child_of"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contact",
            name="name",
            field=models.CharField(
                blank=True,
                default="Anon",
                help_text="Full name in the name order and language user would like. English or 日本語 for example. Max length: 100char",
                max_length=100,
                verbose_name="name",
            ),
        ),
        migrations.AlterField(
            model_name="contact",
            name="name_en",
            field=models.CharField(
                blank=True,
                default="Anon",
                help_text="Full name in English, order should be same as name. Example 田中たろ should become Tanaka Taro in the field. Max length: 100char",
                max_length=100,
                verbose_name="english name",
            ),
        ),
    ]
