# Generated by Django 4.2.1 on 2024-02-16 18:08

from django.db import migrations, models
import streams.customblocks
import wagtail.blocks
import wagtail.fields


class Migration(migrations.Migration):
    dependencies = [
        ("contacts", "0023_remove_contactpage_ja_title_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="contactpage",
            name="assessment_trial",
        ),
        migrations.AddField(
            model_name="contactpage",
            name="trial_en_title",
            field=models.CharField(
                default="Please add",
                help_text="Required. Max length 25, 15 or less is ideal",
                max_length=25,
                verbose_name="Trial - English Title",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="contactpage",
            name="trial_intro",
            field=wagtail.fields.RichTextField(default="Please add"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="contactpage",
            name="trial_jp_title",
            field=models.CharField(
                default="Please add",
                help_text="Required. Max length 20 characters, 15 or less is ideal",
                max_length=20,
                verbose_name="Trial - Japanese Title",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="contactpage",
            name="trial_steps",
            field=wagtail.fields.StreamField(
                [
                    (
                        "info_cards",
                        wagtail.blocks.StructBlock(
                            [
                                (
                                    "title",
                                    wagtail.blocks.CharBlock(
                                        help_text="Title for card. Max length 20",
                                        max_length=20,
                                        required=True,
                                    ),
                                ),
                                (
                                    "image",
                                    streams.customblocks.CustomImageChooserBlock(
                                        help_text="Image size: 2048px x 1280px (16/10 ratio). Please optimize image size before uploading.",
                                        required=False,
                                    ),
                                ),
                                (
                                    "text",
                                    wagtail.blocks.TextBlock(
                                        help_text="Text for card. Max length 100",
                                        max_length=100,
                                        required=True,
                                    ),
                                ),
                            ]
                        ),
                    )
                ],
                null=True,
                use_json_field=True,
            ),
        ),
    ]
