# Generated by Django 4.2.1 on 2024-02-18 16:59

from django.db import migrations, models
import streams.customblocks
import wagtail.blocks
import wagtail.fields


class Migration(migrations.Migration):
    dependencies = [
        ("contacts", "0024_remove_contactpage_assessment_trial_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="contactpage",
            name="join_experience",
        ),
        migrations.AddField(
            model_name="contactpage",
            name="exp_en_title",
            field=models.CharField(
                default="Please add",
                help_text="Required. Max length 25, 15 or less is ideal",
                max_length=25,
                verbose_name="Learning Experiences - English Title",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="contactpage",
            name="exp_intro",
            field=wagtail.fields.RichTextField(
                default="Please add", verbose_name="Learning Experiences - Intro"
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="contactpage",
            name="exp_jp_title",
            field=models.CharField(
                default="Please add",
                help_text="Required. Max length 20 characters, 15 or less is ideal",
                max_length=20,
                verbose_name="Learning Experiences - Japanese Title",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="contactpage",
            name="exp_steps",
            field=wagtail.fields.StreamField(
                [
                    (
                        "info_cards",
                        wagtail.blocks.StructBlock(
                            [
                                (
                                    "title",
                                    wagtail.blocks.CharBlock(
                                        help_text="Title for card. Max length 20",
                                        max_length=20,
                                        required=True,
                                    ),
                                ),
                                (
                                    "image",
                                    streams.customblocks.CustomImageChooserBlock(
                                        help_text="Image size: 2048px x 1280px (16/10 ratio). Please optimize image size before uploading.",
                                        required=False,
                                    ),
                                ),
                                (
                                    "text",
                                    wagtail.blocks.TextBlock(
                                        help_text="Text for card. Max length 100",
                                        max_length=100,
                                        required=True,
                                    ),
                                ),
                            ]
                        ),
                    )
                ],
                null=True,
                use_json_field=True,
            ),
        ),
        migrations.AlterField(
            model_name="contactpage",
            name="trial_intro",
            field=wagtail.fields.RichTextField(verbose_name="Trial - Intro"),
        ),
    ]
