# Generated by Django 4.2.1 on 2024-02-18 18:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("contacts", "0025_remove_contactpage_join_experience_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="contactpage",
            old_name="question_and_answer",
            new_name="qas",
        ),
        migrations.AddField(
            model_name="contactpage",
            name="qa_en_title",
            field=models.CharField(
                default="Please add",
                help_text="Required. Max length 25, 15 or less is ideal",
                max_length=25,
                verbose_name="Learning Experiences - English Title",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="contactpage",
            name="qa_jp_title",
            field=models.CharField(
                default="Please add",
                help_text="Required. Max length 20 characters, 15 or less is ideal",
                max_length=20,
                verbose_name="Learning Experiences - Japanese Title",
            ),
            preserve_default=False,
        ),
    ]
