# Generated by Django 4.2.1 on 2024-02-18 19:36

from django.db import migrations
import wagtail.blocks
import wagtail.fields


class Migration(migrations.Migration):
    dependencies = [
        ("contacts", "0026_rename_question_and_answer_contactpage_qas_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contactpage",
            name="qas",
            field=wagtail.fields.StreamField(
                [
                    (
                        "q_and_a",
                        wagtail.blocks.StructBlock(
                            [
                                (
                                    "question",
                                    wagtail.blocks.CharBlock(
                                        help_text="Your question here. Max length 255",
                                        max_length=255,
                                        required=True,
                                    ),
                                ),
                                (
                                    "answer",
                                    wagtail.blocks.TextBlock(
                                        help_text="The answer to your question here.",
                                        required=True,
                                    ),
                                ),
                            ]
                        ),
                    )
                ],
                null=True,
                use_json_field=True,
            ),
        ),
    ]
