# Generated by Django 4.2.1 on 2024-02-19 07:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("contacts", "0028_contactpage_tel_display_number_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="contactpage",
            name="form_en_title",
            field=models.CharField(
                default="Please add",
                help_text="Required. Max length 25, 15 or less is ideal",
                max_length=25,
                verbose_name="Form - English Title",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="contactpage",
            name="form_jp_title",
            field=models.CharField(
                default="Please add",
                help_text="Required. Max length 20 characters, 15 or less is ideal",
                max_length=20,
                verbose_name="Form - Japanese Title",
            ),
            preserve_default=False,
        ),
    ]
