# Generated by Django 4.2.1 on 2024-07-18 14:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("contacts", "0029_contactpage_form_en_title_contactpage_form_jp_title"),
    ]

    operations = [
        migrations.AddField(
            model_name="contact",
            name="bday",
            field=models.CharField(
                blank=True,
                help_text="Birthday as day and month ex: '10 September'. Max char 20",
                max_length=20,
                verbose_name="birthday",
            ),
        ),
    ]
