# Generated by Django 4.2.1 on 2024-09-23 10:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("contacts", "0030_contact_bday"),
    ]

    operations = [
        migrations.CreateModel(
            name="BannedEmail",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    models.DateTimeField(auto_now_add=True, verbose_name="created"),
                ),
                (
                    "modified",
                    models.DateTimeField(auto_now=True, verbose_name="modified"),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Required. Max 50. Name the emailer uses in mail. Not important, just for convenience",
                        max_length=50,
                        verbose_name="name",
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        help_text="Required. Is unique so can only be one row for this email address. Max 150",
                        max_length=150,
                        unique=True,
                        verbose_name="email address",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
