# Generated by Django 4.2.1 on 2025-01-22 08:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("contacts", "0031_bannedemail"),
    ]

    operations = [
        migrations.AddField(
            model_name="bannedemail",
            name="message",
            field=models.TextField(
                default="No mail associated",
                help_text="Required. Email sent for post mail analysis, for safety sake",
                verbose_name="message",
            ),
        ),
    ]
