# Generated by Django 4.2.1 on 2023-07-26 13:44

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="customuser",
            name="full_en_name",
        ),
        migrations.RemoveField(
            model_name="customuser",
            name="full_name",
        ),
    ]
