# Generated by Django 4.2.1 on 2023-08-14 13:44

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Language",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name_en",
                    models.CharField(
                        help_text="Required. Max length 40 chars",
                        max_length=40,
                        verbose_name="English name",
                    ),
                ),
                (
                    "name_ja",
                    models.CharField(
                        help_text="Required. Max length 40 chars",
                        max_length=40,
                        verbose_name="Japanese Name",
                    ),
                ),
                (
                    "slug",
                    models.CharField(
                        help_text="Required. Use English name to create a slug with only hypens and lowercase letters",
                        max_length=50,
                        unique=True,
                        verbose_name="Slug",
                    ),
                ),
            ],
            options={
                "verbose_name": "Language",
                "verbose_name_plural": "Languages",
            },
        ),
    ]
