# Generated by Django 4.2.1 on 2023-08-14 13:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("wagtailimages", "0025_alter_image_file_alter_rendition_file"),
        ("core", "0001_initial"),
        ("staff", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="staffdetailpage",
            name="country",
            field=models.CharField(
                default="ジンバブエ",
                help_text="Required. Max length 60 chars",
                max_length=60,
                verbose_name="Country",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="staffdetailpage",
            name="native_language",
            field=models.OneToOneField(
                default=1,
                help_text="Required.",
                on_delete=django.db.models.deletion.PROTECT,
                to="core.language",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="staffdetailpage",
            name="profile_image",
            field=models.ForeignKey(
                help_text="Image size: 1000px x 1000px. Please optimize image size before uploading.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="wagtailimages.image",
            ),
        ),
    ]
