# Generated by Django 4.2.1 on 2023-08-14 13:46

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("staff", "0002_staffdetailpage_country_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="staffdetailpage",
            name="native_language",
        ),
    ]
