# Generated by Django 4.2.1 on 2023-08-14 14:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0001_initial"),
        ("staff", "0003_remove_staffdetailpage_native_language"),
    ]

    operations = [
        migrations.AddField(
            model_name="staffdetailpage",
            name="native_language",
            field=models.OneToOneField(
                default=1,
                help_text="Required.",
                on_delete=django.db.models.deletion.PROTECT,
                to="core.language",
            ),
            preserve_default=False,
        ),
    ]
