# Generated by Django 4.2.1 on 2023-08-14 15:12

from django.db import migrations
import wagtail.blocks
import wagtail.fields


class Migration(migrations.Migration):
    dependencies = [
        ("staff", "0005_alter_staffdetailpage_member_languagesspoken"),
    ]

    operations = [
        migrations.AddField(
            model_name="staffdetailpage",
            name="interview",
            field=wagtail.fields.StreamField(
                [
                    (
                        "youtube",
                        wagtail.blocks.StructBlock(
                            [
                                (
                                    "src",
                                    wagtail.blocks.URLBlock(
                                        help_text="Get src from in the youtube embed code, include start if needed.",
                                        max_length=255,
                                        required=True,
                                    ),
                                ),
                                (
                                    "short",
                                    wagtail.blocks.BooleanBlock(
                                        help_text="Tick this box if the video is a short, i.e vertical format",
                                        required=False,
                                    ),
                                ),
                                (
                                    "limit",
                                    wagtail.blocks.BooleanBlock(
                                        help_text="Tick this box if you would like to limit recommended videos to this channel",
                                        required=False,
                                    ),
                                ),
                            ]
                        ),
                    ),
                    (
                        "q_and_a",
                        wagtail.blocks.StructBlock(
                            [
                                (
                                    "q_and_a_series",
                                    wagtail.blocks.ListBlock(
                                        wagtail.blocks.StructBlock(
                                            [
                                                (
                                                    "question",
                                                    wagtail.blocks.CharBlock(
                                                        help_text="Your question here. Max length 255",
                                                        max_length=255,
                                                        required=True,
                                                    ),
                                                ),
                                                (
                                                    "answer",
                                                    wagtail.blocks.TextBlock(
                                                        help_text="The answer to your question here.",
                                                        required=True,
                                                    ),
                                                ),
                                            ]
                                        )
                                    ),
                                )
                            ]
                        ),
                    ),
                ],
                null=True,
                use_json_field=True,
            ),
        ),
    ]
