# Generated by Django 4.2.1 on 2023-09-22 14:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("staff", "0007_staffdetailpage_hobbies_staffdetailpage_role_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="staffdetailpage",
            name="intro",
            field=models.TextField(
                default="Intro - please change",
                help_text="Required.",
                max_length=200,
                verbose_name="Intro",
            ),
            preserve_default=False,
        ),
    ]
