# Generated by Django 4.2.1 on 2024-01-25 11:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("staff", "0008_staffdetailpage_intro"),
    ]

    operations = [
        migrations.AddField(
            model_name="staffdetailpage",
            name="display_name",
            field=models.CharField(
                default="Please add",
                help_text="Required. Max length 25 characters. Staff name as they would like it displayed to the public and in the appropriate langauge",
                max_length=25,
                verbose_name="Display Name",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="staffdetailpage",
            name="display_tagline",
            field=models.CharField(
                default="Please add",
                help_text="Required. Max length 50 characters, 45 or less is ideal. Attractive ,one sentence summary of staff member, shorter than intro.",
                max_length=50,
                verbose_name="Display Tagline",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="staffdetailpage",
            name="intro",
            field=models.TextField(
                help_text="Required. Intro with max 200 char length. To be shown on the detail page for the staff member",
                max_length=200,
                verbose_name="Intro",
            ),
        ),
    ]
