# Generated by Django 4.2.1 on 2024-02-13 08:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0001_initial"),
        ("staff", "0009_staffdetailpage_display_name_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="staffdetailpage",
            name="native_language",
            field=models.ForeignKey(
                help_text="Required.",
                on_delete=django.db.models.deletion.PROTECT,
                to="core.language",
            ),
        ),
    ]
