# Generated by Django 4.2.1 on 2023-11-10 11:09

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("taxes", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="tax",
            options={"verbose_name_plural": "Taxes"},
        ),
    ]
