# Generated by Django 4.2.1 on 2023-08-11 09:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("contacts", "0009_contact_addresses"),
    ]

    operations = [
        migrations.CreateModel(
            name="TelNumber",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    models.DateTimeField(auto_now_add=True, verbose_name="created"),
                ),
                (
                    "modified",
                    models.DateTimeField(auto_now=True, verbose_name="modified"),
                ),
                (
                    "number",
                    models.CharField(
                        help_text="Required, max 15 char",
                        max_length=15,
                        verbose_name="Telephone Number",
                    ),
                ),
                (
                    "number_type",
                    models.CharField(
                        choices=[
                            ("HOF", "Fixed Home Phone"),
                            ("WOF", "Fixed Work Phone"),
                            ("PEM", "Personal mobile"),
                            ("WOM", "Work Mobile"),
                        ],
                        default="PEM",
                        help_text="Required",
                        max_length=3,
                        verbose_name="Type",
                    ),
                ),
                (
                    "is_primary",
                    models.BooleanField(
                        default=False,
                        help_text="Required. Should be only one per place or contact",
                        verbose_name="Is primary",
                    ),
                ),
                (
                    "contact",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="contacts.contact",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
