# Generated by Django 4.2.1 on 2023-08-11 10:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("telnumbers", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="telnumber",
            name="identifier",
            field=models.CharField(
                blank=True,
                help_text="Not required, max 150 char",
                max_length=150,
                verbose_name="Easy Identifier",
            ),
        ),
    ]
