# Generated by Django 4.2.1 on 2023-09-27 04:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("telnumbers", "0002_telnumber_identifier"),
    ]

    operations = [
        migrations.AddField(
            model_name="telnumber",
            name="is_learning_center",
            field=models.BooleanField(default=False, verbose_name="Is Learning Center"),
        ),
    ]
