# Generated by Django 4.2.1 on 2023-09-12 09:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("wagtailcore", "0083_workflowcontenttype"),
    ]

    operations = [
        migrations.CreateModel(
            name="Course",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title_en",
                    models.CharField(
                        help_text="Subject should be included in the title. For example 'Advanced General English'. English will be the subject which also corresponds to the subject choice field",
                        max_length=200,
                        unique=True,
                        verbose_name="English Title",
                    ),
                ),
                (
                    "subject",
                    models.CharField(
                        choices=[
                            ("english", "en,English,英語"),
                            ("japanese", "ja,Japanese,日本語"),
                            ("french", "fr,French,フランス語"),
                        ],
                        default="english",
                        help_text="Required",
                        max_length=20,
                        verbose_name="Subject",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="CourseDisplayDetailPage",
            fields=[
                (
                    "page_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="wagtailcore.page",
                    ),
                ),
                (
                    "display_title",
                    models.CharField(
                        help_text="Required. Max length 100 characters, 45 or less is ideal",
                        max_length=100,
                        verbose_name="Display Title",
                    ),
                ),
                (
                    "course",
                    models.OneToOneField(
                        help_text="The associated course",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="course_detail_page",
                        to="courses.course",
                    ),
                ),
            ],
            options={
                "verbose_name": "Course Display Detail Page",
                "verbose_name_plural": "Course Display Detail Pages",
            },
            bases=("wagtailcore.page",),
        ),
    ]
