# Generated by Django 4.2.1 on 2023-09-12 13:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("courses", "0002_coursedisplaylistpage"),
    ]

    operations = [
        migrations.AddField(
            model_name="coursedisplaydetailpage",
            name="subject_slug",
            field=models.SlugField(
                blank=True,
                help_text="Read only field that get's value from the course field",
                verbose_name="Readonly subect slug field",
            ),
        ),
    ]
