# Generated by Django 4.2.1 on 2023-09-13 13:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("courses", "0006_course_created_course_modified"),
    ]

    operations = [
        migrations.AddField(
            model_name="coursedisplaydetailpage",
            name="level_from",
            field=models.PositiveSmallIntegerField(
                default=1,
                help_text="Starting level. If no 'to level' or this is 'all' levels then please enter 'to level' as None.",
                verbose_name="Level From",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="coursedisplaydetailpage",
            name="level_to",
            field=models.PositiveSmallIntegerField(
                choices=[
                    (0, "None,ない"),
                    (1, "All,全級"),
                    (2, "Elementary,初級"),
                    (3, "Lower Intermediate, 中初級"),
                    (4, "Intermediate,中級 "),
                    (5, "Upper Intermediate,中上級"),
                    (6, "Advanced,上級"),
                ],
                default=0,
                help_text="Starting level. If no 'to level' then please mark 'to level' as None.",
                verbose_name="Level To",
            ),
        ),
    ]
