# Generated by Django 4.2.1 on 2023-09-13 14:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("courses", "0007_coursedisplaydetailpage_level_from_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="coursedisplaydetailpage",
            name="course_category",
            field=models.PositiveSmallIntegerField(
                choices=[
                    (0, "General,日常"),
                    (1, "Business,ビジネス"),
                    (2, "Test Preparation,テスト対策"),
                    (3, "Writing, ライティング"),
                ],
                default=0,
                help_text="Course category for the course, if in doubt make it general",
                verbose_name="Course Category",
            ),
        ),
        migrations.AlterField(
            model_name="coursedisplaydetailpage",
            name="level_from",
            field=models.PositiveSmallIntegerField(
                choices=[
                    (0, "None,ない"),
                    (1, "All,全級"),
                    (2, "Elementary,初級"),
                    (3, "Lower Intermediate, 中初級"),
                    (4, "Intermediate,中級 "),
                    (5, "Upper Intermediate,中上級"),
                    (6, "Advanced,上級"),
                ],
                help_text="Starting level. If no 'to level' or this is 'all' levels then please enter 'to level' as None.",
                verbose_name="Level From",
            ),
        ),
    ]
