# Generated by Django 4.2.1 on 2023-09-14 08:39

from django.db import migrations
import wagtail.blocks
import wagtail.fields


class Migration(migrations.Migration):
    dependencies = [
        ("courses", "0009_coursedisplaydetailpage_course_description_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="coursedisplaydetailpage",
            name="course_content_points",
            field=wagtail.fields.StreamField(
                [
                    (
                        "listblock",
                        wagtail.blocks.StructBlock(
                            [
                                (
                                    "liste",
                                    wagtail.blocks.ListBlock(
                                        wagtail.blocks.StructBlock(
                                            [
                                                (
                                                    "list_item",
                                                    wagtail.blocks.CharBlock(
                                                        help_text="Max length 30chars.",
                                                        max_length=30,
                                                    ),
                                                )
                                            ]
                                        )
                                    ),
                                )
                            ]
                        ),
                    )
                ],
                null=True,
                use_json_field=True,
            ),
        ),
    ]
