# Generated by Django 4.2.1 on 2023-09-20 08:08

from django.db import migrations, models
import streams.customblocks
import wagtail.blocks
import wagtail.fields


class Migration(migrations.Migration):
    dependencies = [
        ("courses", "0011_coursedisplaydetailpage_display_intro_relatedcourse"),
    ]

    operations = [
        migrations.AlterField(
            model_name="coursedisplaydetailpage",
            name="course_description",
            field=wagtail.fields.StreamField(
                [
                    ("rich_text", streams.customblocks.CustomRichTextBlock()),
                    (
                        "text_width_img",
                        wagtail.blocks.StructBlock(
                            [
                                (
                                    "image",
                                    streams.customblocks.CustomImageChooserBlock(
                                        help_text="Required. Image size: 2048px x 1280px (16/10 ratio)",
                                        required=True,
                                    ),
                                ),
                                (
                                    "caption",
                                    wagtail.blocks.CharBlock(
                                        help_text="Optional. Caption, max length = 200",
                                        max_length=200,
                                        required=False,
                                    ),
                                ),
                                (
                                    "author",
                                    wagtail.blocks.CharBlock(
                                        help_text="Optional. The image creators name if attribution is required or nice to do, max length = 50",
                                        max_length=50,
                                        required=False,
                                    ),
                                ),
                                (
                                    "attribution_url",
                                    wagtail.blocks.URLBlock(
                                        help_text="Optional. The url to the author or image place, max length = 100",
                                        max_length=100,
                                        required=False,
                                    ),
                                ),
                                (
                                    "license_type",
                                    wagtail.blocks.CharBlock(
                                        help_text="Optional. The type of license, eg: Creative Commons. max length = 50",
                                        max_length=50,
                                        required=False,
                                    ),
                                ),
                                (
                                    "license_url",
                                    wagtail.blocks.URLBlock(
                                        help_text="Optional. The link to relevant license. max length = 100",
                                        max_length=100,
                                        required=False,
                                    ),
                                ),
                            ]
                        ),
                    ),
                    (
                        "youtube",
                        wagtail.blocks.StructBlock(
                            [
                                (
                                    "src",
                                    wagtail.blocks.URLBlock(
                                        help_text="Get src from in the youtube embed code, include start if needed.",
                                        max_length=255,
                                        required=True,
                                    ),
                                ),
                                (
                                    "short",
                                    wagtail.blocks.BooleanBlock(
                                        help_text="Tick this box if the video is a short, i.e vertical format",
                                        required=False,
                                    ),
                                ),
                                (
                                    "limit",
                                    wagtail.blocks.BooleanBlock(
                                        help_text="Tick this box if you would like to limit recommended videos to this channel",
                                        required=False,
                                    ),
                                ),
                            ]
                        ),
                    ),
                ],
                null=True,
                use_json_field=True,
            ),
        ),
        migrations.AlterField(
            model_name="coursedisplaydetailpage",
            name="level_from",
            field=models.PositiveSmallIntegerField(
                choices=[
                    (0, "None,ない"),
                    (1, "All,全級"),
                    (2, "Elementary,初級"),
                    (3, "Lower Intermediate, 中初級"),
                    (4, "Intermediate,中級 "),
                    (5, "Upper Intermediate,中上級"),
                    (6, "Advanced,上級"),
                    (7, "Grade 1,1級"),
                    (8, "Grade Pre-1,準1級"),
                    (9, "Grade 2,2級"),
                    (10, "Grade Pre-2,準2級"),
                    (11, "Grade 3,3級"),
                    (12, "Grade 4,4級"),
                    (13, "Grade 5,5級"),
                ],
                help_text="Starting level. If no 'to level' or this is 'all' levels then please enter 'to level' as None.",
                verbose_name="Level From",
            ),
        ),
        migrations.AlterField(
            model_name="coursedisplaydetailpage",
            name="level_to",
            field=models.PositiveSmallIntegerField(
                choices=[
                    (0, "None,ない"),
                    (1, "All,全級"),
                    (2, "Elementary,初級"),
                    (3, "Lower Intermediate, 中初級"),
                    (4, "Intermediate,中級 "),
                    (5, "Upper Intermediate,中上級"),
                    (6, "Advanced,上級"),
                    (7, "Grade 1,1級"),
                    (8, "Grade Pre-1,準1級"),
                    (9, "Grade 2,2級"),
                    (10, "Grade Pre-2,準2級"),
                    (11, "Grade 3,3級"),
                    (12, "Grade 4,4級"),
                    (13, "Grade 5,5級"),
                ],
                default=0,
                help_text="Starting level. If no 'to level' then please mark 'to level' as None.",
                verbose_name="Level To",
            ),
        ),
    ]
