# Generated by Django 4.2.1 on 2023-12-12 15:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("courses", "0012_alter_coursedisplaydetailpage_course_description_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="coursedisplaydetailpage",
            name="course_category",
        ),
        migrations.AddField(
            model_name="course",
            name="course_category",
            field=models.CharField(
                choices=[
                    ("general", "General,日常"),
                    ("business", "Business,ビジネス"),
                    ("test-preparation", "Test Preparation,テスト対策"),
                    ("writing", "Writing,ライティング"),
                ],
                default="general",
                help_text="Course category for the course, if in doubt make it general",
                verbose_name="Course Category",
            ),
        ),
        migrations.AddField(
            model_name="course",
            name="description",
            field=models.TextField(
                default="Please ADD DESCRIPTION",
                help_text="A brief description of the course for internal use",
                max_length=300,
                verbose_name="Description",
            ),
            preserve_default=False,
        ),
    ]
