# Generated by Django 4.2.1 on 2023-12-13 09:37

from django.db import migrations, models
import django.db.models.deletion
import modelcluster.fields


class Migration(migrations.Migration):
    dependencies = [
        ("courses", "0013_remove_coursedisplaydetailpage_course_category_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="coursedisplaylistpage",
            options={
                "verbose_name": "Course List Page",
                "verbose_name_plural": "Courses List Pages",
            },
        ),
        migrations.AddField(
            model_name="coursedisplaylistpage",
            name="display_tagline",
            field=models.CharField(
                default="PLEASE ADD",
                help_text="Required. Max length 160 char. A catchy, attractive tagline to give more information and sell the courses in general",
                max_length=160,
                verbose_name="Disply Tagline",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="coursedisplaylistpage",
            name="en_sec_dis_tagline",
            field=models.CharField(
                default="PLEASE ADD",
                help_text="Required. Max length 160 char. A catchy, attractive tagline to give more information and sell the english courses in general",
                max_length=160,
                verbose_name="English Section Display Tagline",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="coursedisplaylistpage",
            name="en_sec_dis_title",
            field=models.CharField(
                default="PLEASE ADD",
                help_text="Required. In display language. Max length 100 characters, 45 or less is ideal",
                max_length=100,
                verbose_name="English Section Display Title",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="coursedisplaylistpage",
            name="en_sec_other_title",
            field=models.CharField(
                default="PLEASE ADD",
                help_text="Required. Max length 100 char in display language",
                max_length=100,
                verbose_name="Other English Courses Title",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="coursedisplaylistpage",
            name="en_sec_pop_title",
            field=models.CharField(
                default="PLEASE ADD",
                help_text="Required. Max length 100 char in display language",
                max_length=100,
                verbose_name="Popular English Courses Title",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="coursedisplaylistpage",
            name="en_sec_title",
            field=models.CharField(
                default="PLEASE ADD",
                help_text="Required. In English please. Max length 100 characters, 45 or less is ideal",
                max_length=100,
                verbose_name="English Section Title",
            ),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name="PopularEnglishCourse",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "sort_order",
                    models.IntegerField(blank=True, editable=False, null=True),
                ),
                (
                    "course",
                    models.ForeignKey(
                        limit_choices_to={"subject_slug": "english"},
                        on_delete=django.db.models.deletion.CASCADE,
                        to="courses.coursedisplaydetailpage",
                    ),
                ),
                (
                    "page",
                    modelcluster.fields.ParentalKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pop_en_courses",
                        to="courses.coursedisplaylistpage",
                    ),
                ),
            ],
            options={
                "ordering": ["sort_order"],
                "abstract": False,
            },
        ),
    ]
