# Generated by Django 4.2.1 on 2024-03-16 05:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("courses", "0018_alter_course_course_category"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="coursedisplaylistpage",
            name="display_tagline",
        ),
        migrations.RemoveField(
            model_name="coursedisplaylistpage",
            name="en_sec_dis_tagline",
        ),
        migrations.RemoveField(
            model_name="coursedisplaylistpage",
            name="en_sec_dis_title",
        ),
        migrations.RemoveField(
            model_name="coursedisplaylistpage",
            name="en_sec_other_title",
        ),
        migrations.RemoveField(
            model_name="coursedisplaylistpage",
            name="en_sec_pop_title",
        ),
        migrations.RemoveField(
            model_name="coursedisplaylistpage",
            name="en_sec_title",
        ),
        migrations.AlterField(
            model_name="coursedisplaylistpage",
            name="display_title",
            field=models.CharField(
                help_text="Required. Max length 15 characters. Japanese",
                max_length=15,
                verbose_name="Display Title",
            ),
        ),
    ]
