# Generated by Django 4.2.1 on 2024-03-25 06:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("courses", "0021_coursedisplaylistpage_english_en_title_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="course",
            name="course_category",
            field=models.CharField(
                choices=[
                    ("general", "General,日常"),
                    ("business", "Business,ビジネス"),
                    ("testpreparation", "Test Preparation,テスト対策"),
                    ("writing", "Writing,ライティング"),
                ],
                default="general",
                help_text="Course category for the course, if in doubt make it general",
                max_length=20,
                verbose_name="Course Category",
            ),
        ),
    ]
