# Generated by Django 4.2.1 on 2024-03-28 07:37

from django.db import migrations, models
import django.db.models.deletion
import modelcluster.fields


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0042_alter_classpricesdetailpage_class_intro"),
        ("courses", "0022_alter_course_course_category"),
    ]

    operations = [
        migrations.CreateModel(
            name="CommonPricePlans",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "sort_order",
                    models.IntegerField(blank=True, editable=False, null=True),
                ),
                (
                    "page",
                    modelcluster.fields.ParentalKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="common_price_plans",
                        to="courses.coursedisplaydetailpage",
                    ),
                ),
                (
                    "price_plan",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="products.classpricesdetailpage",
                    ),
                ),
            ],
            options={
                "ordering": ["sort_order"],
                "abstract": False,
            },
        ),
    ]
