# Generated by Django 4.2.1 on 2024-03-28 14:53

from django.db import migrations
import wagtail.blocks
import wagtail.fields


class Migration(migrations.Migration):
    dependencies = [
        ("courses", "0023_commonpriceplans"),
    ]

    operations = [
        migrations.AlterField(
            model_name="coursedisplaydetailpage",
            name="course_content_points",
            field=wagtail.fields.StreamField(
                [
                    (
                        "short_text_block",
                        wagtail.blocks.StructBlock(
                            [
                                (
                                    "text",
                                    wagtail.blocks.CharBlock(
                                        help_text="Required. Max length 35 chars",
                                        max_length=35,
                                        required=True,
                                    ),
                                )
                            ]
                        ),
                    )
                ],
                null=True,
                use_json_field=True,
            ),
        ),
    ]
