# Generated by Django 4.2.1 on 2023-09-27 05:13

from django.db import migrations, models
import django.db.models.deletion
import wagtail.fields


class Migration(migrations.Migration):
    dependencies = [
        ("wagtailcore", "0091_alter_page_title"),
        ("learningcenters", "0003_rename_learningcenterpage_learningcenterdetailpage"),
    ]

    operations = [
        migrations.CreateModel(
            name="LearningCenterListPage",
            fields=[
                (
                    "page_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="wagtailcore.page",
                    ),
                ),
                (
                    "display_title",
                    models.CharField(
                        help_text="Required. Max length 100 characters, 45 or less is ideal",
                        max_length=100,
                        verbose_name="Display Title",
                    ),
                ),
                (
                    "display_intro",
                    wagtail.fields.RichTextField(
                        help_text="Required.", verbose_name="Display Introduction"
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
            bases=("wagtailcore.page",),
        ),
    ]
