# Generated by Django 4.2.1 on 2024-01-10 08:51

from django.db import migrations, models
import django.db.models.deletion
import wagtail.fields


class Migration(migrations.Migration):
    dependencies = [
        ("wagtailimages", "0025_alter_image_file_alter_rendition_file"),
        ("home", "0002_create_homepage"),
    ]

    operations = [
        migrations.AddField(
            model_name="homepage",
            name="why_content",
            field=wagtail.fields.RichTextField(default="ADD CONTENT"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="homepage",
            name="why_en_title",
            field=models.CharField(
                default="ADD CONTENT",
                help_text="Required. Max length 25 characters, 20 or less is ideal",
                max_length=25,
                verbose_name="Why - English Title",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="homepage",
            name="why_image",
            field=models.ForeignKey(
                help_text="Image size: 2048px x 1280px. Please optimize image size before uploading.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="wagtailimages.image",
            ),
        ),
        migrations.AddField(
            model_name="homepage",
            name="why_jp_title",
            field=models.CharField(
                default="ADD CONTENT",
                help_text="Required. Max length 20 characters, 15 or less is ideal",
                max_length=20,
                verbose_name="Why - Japanese Title",
            ),
            preserve_default=False,
        ),
    ]
