# Generated by Django 4.2.1 on 2024-01-10 18:16

from django.db import migrations, models
import streams.customblocks
import wagtail.blocks
import wagtail.fields


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0003_homepage_why_content_homepage_why_en_title_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="homepage",
            name="service_cards",
            field=wagtail.fields.StreamField(
                [
                    (
                        "square_pic_cards",
                        wagtail.blocks.StructBlock(
                            [
                                (
                                    "image",
                                    streams.customblocks.CustomSquareImageChooserBlock(
                                        help_text="Image size: 2048px x 2048px (1/1 ratio). Please optimize image before uploading.",
                                        required=True,
                                    ),
                                ),
                                (
                                    "title",
                                    wagtail.blocks.CharBlock(
                                        help_text="Title for card. Max length 25",
                                        max_length=25,
                                        required=True,
                                    ),
                                ),
                                (
                                    "text",
                                    wagtail.blocks.TextBlock(
                                        help_text="Text for card. Max length 150",
                                        max_length=150,
                                        required=True,
                                    ),
                                ),
                                (
                                    "link",
                                    wagtail.blocks.CharBlock(
                                        help_text="Link url. Not required",
                                        max_length=150,
                                        required=False,
                                    ),
                                ),
                            ],
                            label="Service Card",
                        ),
                    )
                ],
                blank=True,
                use_json_field=True,
            ),
        ),
        migrations.AddField(
            model_name="homepage",
            name="service_en_title",
            field=models.CharField(
                default="ADD CONTENT",
                help_text="Required.",
                verbose_name="Services - Content",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="homepage",
            name="service_jp_title",
            field=models.CharField(
                default="ADD CONTENT",
                help_text="Required. Max length 20 characters, 15 or less is ideal",
                max_length=20,
                verbose_name="Services - Japanese Title",
            ),
            preserve_default=False,
        ),
    ]
