# Generated by Django 4.2.1 on 2024-01-11 12:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0004_homepage_service_cards_homepage_service_en_title_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="homepage",
            name="service_en_title",
            field=models.CharField(
                help_text="Required.", verbose_name="Services - English Title"
            ),
        ),
    ]
