# Generated by Django 4.2.1 on 2024-01-19 03:40

from django.db import migrations, models
import django.db.models.deletion
import modelcluster.fields


class Migration(migrations.Migration):
    dependencies = [
        ("testimonials", "0005_alter_testimonialdetailpage_customer_interview"),
        ("home", "0005_alter_homepage_service_en_title"),
    ]

    operations = [
        migrations.AddField(
            model_name="homepage",
            name="testimonial_en_title",
            field=models.CharField(
                default="FILL IN PLEASE",
                help_text="Required. Max length 25, 15 or less is ideal",
                max_length=25,
                verbose_name="Testimonials - English Title",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="homepage",
            name="testimonial_jp_title",
            field=models.CharField(
                default="FILL IN PLEASE",
                help_text="Required. Max length 20 characters, 15 or less is ideal",
                max_length=20,
                verbose_name="Testimonials - Japanese Title",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="homepage",
            name="service_en_title",
            field=models.CharField(
                help_text="Required. Max length 25, 15 or less is ideal",
                max_length=25,
                verbose_name="Services - English Title",
            ),
        ),
        migrations.CreateModel(
            name="HomeTestimonials",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "sort_order",
                    models.IntegerField(blank=True, editable=False, null=True),
                ),
                (
                    "page",
                    modelcluster.fields.ParentalKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="home_testimonials",
                        to="home.homepage",
                    ),
                ),
                (
                    "testimonial",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="testimonials.testimonialdetailpage",
                    ),
                ),
            ],
            options={
                "ordering": ["sort_order"],
                "abstract": False,
            },
        ),
    ]
