# Generated by Django 4.2.1 on 2024-01-25 09:05

from django.db import migrations, models
import django.db.models.deletion
import modelcluster.fields


class Migration(migrations.Migration):
    dependencies = [
        ("staff", "0008_staffdetailpage_intro"),
        ("home", "0007_homepage_price_en_title_homepage_price_jp_title_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="homepage",
            name="teacher_en_title",
            field=models.CharField(
                default="Please update this",
                help_text="Required. Max length 25, 15 or less is ideal",
                max_length=25,
                verbose_name="Teachers - English Title",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="homepage",
            name="teacher_jp_title",
            field=models.CharField(
                default="Please update this",
                help_text="Required. Max length 20 characters, 15 or less is ideal",
                max_length=20,
                verbose_name="Teachers - Japanese Title",
            ),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name="HomeTeachers",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "sort_order",
                    models.IntegerField(blank=True, editable=False, null=True),
                ),
                (
                    "page",
                    modelcluster.fields.ParentalKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="home_teachers",
                        to="home.homepage",
                    ),
                ),
                (
                    "teacher",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="staff.staffdetailpage",
                    ),
                ),
            ],
            options={
                "ordering": ["sort_order"],
                "abstract": False,
            },
        ),
    ]
