# Generated by Django 4.2.1 on 2024-02-13 15:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0008_homepage_teacher_en_title_homepage_teacher_jp_title_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="homepage",
            name="bloglesson_en_title",
            field=models.CharField(
                default="Please add",
                help_text="Required. Max length 25, 15 or less is ideal",
                max_length=25,
                verbose_name="Blog Lessons - English Title",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="homepage",
            name="bloglesson_jp_title",
            field=models.CharField(
                default="Please add",
                help_text="Required. Max length 20 characters, 15 or less is ideal",
                max_length=20,
                verbose_name="Blog Lessons - Japanese Title",
            ),
            preserve_default=False,
        ),
    ]
