from django.db import models
from django.utils.translation import gettext_lazy as _
from django.utils.text import slugify
from django.core.exceptions import ValidationError

from core.models import TimeStampedModel

# =====================
# Model Choices
# =====================


class ProductServiceTypeChoices(models.TextChoices):
    CLASS = "class", _("Class")
    EXPERIENCE = "experience", _("Learning Experience")
    BOOK = "book", _("Book")


class ProductOrServiceChoices(models.TextChoices):
    SERVICE = "service", _("Service")
    PRODUCT = "product", _("Product")


# =====================
# Models
# =====================


class ProductService(TimeStampedModel):
    """Model for all products and services sold by the company"""

    name = models.CharField(
        _("Name"),
        blank=False,
        null=False,
        max_length=200,
        help_text=_("Required. Max length 200 characters."),
    )
    slug = models.SlugField(
        _("Slug"),
        null=False,
        blank=False,
        unique=True,
        editable=False,
        max_length=100,
        help_text=_(
            "Autogenerated slug. Base slug for product model and any product display model"
        ),
    )
    service_or_product = models.CharField(
        _("Service or Product"),
        null=False,
        blank=False,
        choices=ProductOrServiceChoices.choices,
        help_text="Required",
    )
    ptype = models.CharField(
        _("Product Type"),
        null=False,
        blank=False,
        choices=ProductServiceTypeChoices.choices,
        help_text="Required",
    )

    def __str__(self):
        return self.name

    def _get_slug_or_raise_custom_error(self):
        slug = slugify(self.name)
        unique_slug = slug

        if not ProductService.objects.filter(slug=unique_slug).exists():
            return unique_slug
        else:
            # Is own slug
            if ProductService.objects.filter(slug=unique_slug)[0].id == self.id:
                return unique_slug

            else:
                similar_object = ProductService.objects.filter(slug=unique_slug)[0]
                raise ValidationError(
                    f"The slug value {unique_slug} indicates this product is not unique. It is similar to the product with name: {similar_object.name}  and id:  {similar_object.id}"
                )

    def clean(self):
        self.slug = self._get_slug_or_raise_custom_error()

    def save(self, *args, **kwargs):
        self.clean()
        super().save(*args, **kwargs)
