# Generated by Django 4.2.1 on 2023-09-21 15:30

from django.db import migrations, models
import django.db.models.deletion
import modelcluster.fields
import streams.customblocks
import wagtail.blocks
import wagtail.fields


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("wagtailcore", "0090_alter_page_title"),
        ("staff", "0007_staffdetailpage_hobbies_staffdetailpage_role_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="AboutPage",
            fields=[
                (
                    "page_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="wagtailcore.page",
                    ),
                ),
                (
                    "display_title",
                    models.CharField(
                        help_text="Required. Max length 15 characters. English",
                        max_length=15,
                        verbose_name="Display Title",
                    ),
                ),
                (
                    "mission_title",
                    models.CharField(
                        help_text="Required. Max length 15 characters.",
                        max_length=15,
                        verbose_name="Mission Title",
                    ),
                ),
                (
                    "mission_tagline",
                    models.CharField(
                        help_text="Required. Max length 100 characters. Japanese",
                        max_length=100,
                        verbose_name="Mission Tagline",
                    ),
                ),
                (
                    "mission_content",
                    models.TextField(
                        help_text="Required. Max length 300 characters.",
                        max_length=300,
                        verbose_name="Mission Content",
                    ),
                ),
                (
                    "staff_title",
                    models.CharField(
                        help_text="Required. Max length 15 characters.",
                        max_length=15,
                        verbose_name="Staff Title",
                    ),
                ),
                (
                    "staff_tagline",
                    models.CharField(
                        help_text="Required. Max length 100 characters. Japanese",
                        max_length=100,
                        verbose_name="Staff Tagline",
                    ),
                ),
                (
                    "values_title",
                    models.CharField(
                        help_text="Required. Max length 15 characters.",
                        max_length=15,
                        verbose_name="Core Values Title",
                    ),
                ),
                (
                    "values_tagline",
                    models.CharField(
                        help_text="Required. Max length 100 characters. Japanese",
                        max_length=100,
                        verbose_name="Core Values Tagline",
                    ),
                ),
                (
                    "values_cards",
                    wagtail.fields.StreamField(
                        [
                            (
                                "value_cards",
                                wagtail.blocks.StructBlock(
                                    [
                                        (
                                            "cards",
                                            wagtail.blocks.ListBlock(
                                                wagtail.blocks.StructBlock(
                                                    [
                                                        (
                                                            "title",
                                                            wagtail.blocks.CharBlock(
                                                                help_text="Title for card. Max length 20",
                                                                max_length=20,
                                                                required=True,
                                                            ),
                                                        ),
                                                        (
                                                            "image",
                                                            streams.customblocks.CustomImageChooserBlock(
                                                                help_text="Image size: 2048px x 1280px (16/10 ratio). Please optimize image size before uploading.",
                                                                required=True,
                                                            ),
                                                        ),
                                                        (
                                                            "text",
                                                            wagtail.blocks.TextBlock(
                                                                help_text="Text for card. Max length 100",
                                                                max_length=100,
                                                                required=True,
                                                            ),
                                                        ),
                                                    ]
                                                )
                                            ),
                                        )
                                    ]
                                ),
                            )
                        ],
                        null=True,
                        use_json_field=True,
                    ),
                ),
                (
                    "history_title",
                    models.CharField(
                        help_text="Required. Max length 15 characters.",
                        max_length=15,
                        verbose_name="History Title",
                    ),
                ),
                (
                    "history_tagline",
                    models.CharField(
                        help_text="Required. Max length 100 characters. Japanese",
                        max_length=100,
                        verbose_name="History Tagline",
                    ),
                ),
                (
                    "history_content",
                    wagtail.fields.StreamField(
                        [("rich_text", streams.customblocks.CustomRichTextBlock())],
                        null=True,
                        use_json_field=True,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
            bases=("wagtailcore.page",),
        ),
        migrations.CreateModel(
            name="AboutPageStaff",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "sort_order",
                    models.IntegerField(blank=True, editable=False, null=True),
                ),
                (
                    "page",
                    modelcluster.fields.ParentalKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="staff_members",
                        to="about.aboutpage",
                    ),
                ),
                (
                    "staff",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="staff.staffdetailpage",
                    ),
                ),
            ],
            options={
                "ordering": ["sort_order"],
                "abstract": False,
            },
        ),
    ]
