# Generated by Django 4.2.1 on 2024-02-15 11:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("about", "0002_remove_aboutpage_values_cards_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="aboutpage",
            name="mission_tagline",
        ),
        migrations.RemoveField(
            model_name="aboutpage",
            name="mission_title",
        ),
        migrations.AddField(
            model_name="aboutpage",
            name="mission_en_title",
            field=models.CharField(
                default="Please Enter",
                help_text="Required. Max length 25, 15 or less is ideal",
                max_length=25,
                verbose_name="Mission Title",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="aboutpage",
            name="mission_jp_title",
            field=models.CharField(
                default="Please enter",
                help_text="Required. Max length 20 characters, 15 or less is ideal",
                max_length=20,
                verbose_name="Mission - Japanese Title",
            ),
            preserve_default=False,
        ),
    ]
