# Generated by Django 4.2.1 on 2024-02-15 11:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("about", "0003_remove_aboutpage_mission_tagline_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="aboutpage",
            name="staff_tagline",
        ),
        migrations.RemoveField(
            model_name="aboutpage",
            name="staff_title",
        ),
        migrations.AddField(
            model_name="aboutpage",
            name="staff_en_title",
            field=models.CharField(
                default="Please add",
                help_text="Required. Max length 25, 15 or less is ideal",
                max_length=25,
                verbose_name="Staff - English Title",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="aboutpage",
            name="staff_jp_title",
            field=models.CharField(
                default="Please add",
                help_text="Required. Max length 20 characters, 15 or less is ideal",
                max_length=20,
                verbose_name="Staff - Japanese Title",
            ),
            preserve_default=False,
        ),
    ]
