# Generated by Django 4.2.1 on 2024-02-15 18:14

from django.db import migrations, models
import streams.customblocks
import wagtail.blocks
import wagtail.fields


class Migration(migrations.Migration):
    dependencies = [
        ("about", "0004_remove_aboutpage_staff_tagline_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="aboutpage",
            name="values_content",
        ),
        migrations.RemoveField(
            model_name="aboutpage",
            name="values_tagline",
        ),
        migrations.RemoveField(
            model_name="aboutpage",
            name="values_title",
        ),
        migrations.AddField(
            model_name="aboutpage",
            name="values_en_title",
            field=models.CharField(
                default="Please add",
                help_text="Required. Max length 25, 15 or less is ideal",
                max_length=25,
                verbose_name="Values - English Title",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="aboutpage",
            name="values_intro",
            field=wagtail.fields.RichTextField(default="Please add"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="aboutpage",
            name="values_jp_title",
            field=models.CharField(
                default="Please add",
                help_text="Required. Max length 20 characters, 15 or less is ideal",
                max_length=20,
                verbose_name="Values - Japanese Title",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="aboutpage",
            name="values_list",
            field=wagtail.fields.StreamField(
                [
                    (
                        "value_cards",
                        wagtail.blocks.StructBlock(
                            [
                                (
                                    "title",
                                    wagtail.blocks.CharBlock(
                                        help_text="English title for card. Max length 14",
                                        max_length=14,
                                        required=True,
                                    ),
                                ),
                                (
                                    "jp_title",
                                    wagtail.blocks.CharBlock(
                                        help_text="Japanese Title for card. Max length 10",
                                        max_length=10,
                                        required=True,
                                    ),
                                ),
                                (
                                    "image",
                                    streams.customblocks.CustomImageChooserBlock(
                                        help_text="Image size: 2048px x 1280px (16/10 ratio). Please optimize image size before uploading.",
                                        required=True,
                                    ),
                                ),
                                (
                                    "text",
                                    wagtail.blocks.TextBlock(
                                        help_text="Text for card. Max length 100",
                                        max_length=100,
                                        required=True,
                                    ),
                                ),
                            ]
                        ),
                    )
                ],
                null=True,
                use_json_field=True,
            ),
        ),
    ]
