# Generated by Django 4.2.1 on 2024-02-16 04:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("about", "0005_remove_aboutpage_values_content_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="aboutpage",
            name="history_tagline",
        ),
        migrations.RemoveField(
            model_name="aboutpage",
            name="history_title",
        ),
        migrations.AddField(
            model_name="aboutpage",
            name="history_en_title",
            field=models.CharField(
                default="Please add",
                help_text="Required. Max length 25, 15 or less is ideal",
                max_length=25,
                verbose_name="History - English Title",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="aboutpage",
            name="history_jp_title",
            field=models.CharField(
                default="Please add",
                help_text="Required. Max length 20 characters, 15 or less is ideal",
                max_length=20,
                verbose_name="History - Japanese Title",
            ),
            preserve_default=False,
        ),
    ]
