# Generated by Django 4.2.1 on 2024-08-08 08:34

from decimal import Decimal
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Campaign",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    models.DateTimeField(auto_now_add=True, verbose_name="created"),
                ),
                (
                    "modified",
                    models.DateTimeField(auto_now=True, verbose_name="modified"),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Required. 100 Char max. Campaign name in English",
                        max_length=100,
                        verbose_name="Name",
                    ),
                ),
                (
                    "start_date",
                    models.DateField(help_text="Required", verbose_name="Start Date"),
                ),
                (
                    "end_date",
                    models.DateField(help_text="Required", verbose_name="End Date"),
                ),
                (
                    "description",
                    models.TextField(
                        help_text="Description of key elements of campaign",
                        verbose_name="Campaign Description",
                    ),
                ),
                (
                    "total_customer_increase",
                    models.PositiveSmallIntegerField(
                        default=0,
                        help_text="Required. Completed after campaign results finalized",
                        verbose_name="Total Customer Increase",
                    ),
                ),
                (
                    "monthly_recurring_revenue_increase",
                    models.DecimalField(
                        decimal_places=0,
                        default=Decimal("0"),
                        help_text="Required. Completed after campaign results finalized in yen",
                        max_digits=10,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0"))
                        ],
                        verbose_name="Monthly Rec Rev Increase",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
