# Generated by Django 4.2.1 on 2024-08-08 09:28

from decimal import Decimal
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("campaigns", "0002_campaign_smart_goals_achieved_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="campaign",
            name="description",
            field=models.TextField(
                default="[BRIEF]\n\n[SMART GOALS]\n\nS: \n\nM: \n\nA: \n\nR: \n\nT: \n\n[CHANNELS TO BE USED]\n\n",
                help_text="Description of key elements of campaign. Please use SMART here.",
                verbose_name="Campaign Description",
            ),
        ),
        migrations.AlterField(
            model_name="campaign",
            name="monthly_recurring_revenue_increase",
            field=models.DecimalField(
                decimal_places=0,
                default=Decimal("0"),
                help_text="Required. Completed after campaign results finalized in yen",
                max_digits=10,
                validators=[django.core.validators.MinValueValidator(Decimal("0"))],
                verbose_name="Monthly Rec Rev Increase (￥)",
            ),
        ),
    ]
