# Generated by Django 4.2.1 on 2024-11-28 10:32

from django.db import migrations, models
import django.db.models.deletion
import streams.customblocks
import wagtail.blocks
import wagtail.fields
import wagtail_headless_preview.models


class Migration(migrations.Migration):
    dependencies = [
        ("wagtailimages", "0025_alter_image_file_alter_rendition_file"),
        ("wagtailcore", "0091_remove_revision_submitted_for_moderation"),
        ("campaigns", "0004_campaignlistpage_campaignsimplebannerpage"),
    ]

    operations = [
        migrations.CreateModel(
            name="CampaignImageBannerPage",
            fields=[
                (
                    "page_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="wagtailcore.page",
                    ),
                ),
                (
                    "campaign_page_type",
                    models.CharField(
                        default="image_banner",
                        editable=False,
                        help_text="Auto generated",
                        max_length=20,
                        verbose_name="Campaign Page Type",
                    ),
                ),
                (
                    "name_ja",
                    models.CharField(
                        help_text="Required. Max length 18 chars. Will be name of campaign displayed in the title tag for the page ",
                        max_length=18,
                        verbose_name="Japanese Campaign Name",
                    ),
                ),
                (
                    "tagline",
                    models.CharField(
                        help_text="Required. Max length 100 chars. Succint additional Japanese text to add marketing value to the description tag",
                        max_length=100,
                        verbose_name="Tagline",
                    ),
                ),
                (
                    "start_date",
                    models.DateField(
                        blank=True,
                        help_text="Read only field that gets value from 'campaign'",
                        verbose_name="Start Date",
                    ),
                ),
                (
                    "end_date",
                    models.DateField(
                        blank=True,
                        help_text="Read only field that gets value from 'campaign'",
                        verbose_name="End Date",
                    ),
                ),
                (
                    "additional_details",
                    wagtail.fields.StreamField(
                        [
                            ("rich_text", streams.customblocks.CustomRichTextBlock()),
                            (
                                "text_width_img",
                                wagtail.blocks.StructBlock(
                                    [
                                        (
                                            "image",
                                            streams.customblocks.CustomImageChooserBlock(
                                                help_text="Required. Image size: 2048px x 1280px (16/10 ratio)",
                                                required=True,
                                            ),
                                        ),
                                        (
                                            "caption",
                                            wagtail.blocks.CharBlock(
                                                help_text="Optional. Caption, max length = 200",
                                                max_length=200,
                                                required=False,
                                            ),
                                        ),
                                        (
                                            "author",
                                            wagtail.blocks.CharBlock(
                                                help_text="Optional. The image creators name if attribution is required or nice to do, max length = 50",
                                                max_length=50,
                                                required=False,
                                            ),
                                        ),
                                        (
                                            "attribution_url",
                                            wagtail.blocks.URLBlock(
                                                help_text="Optional. The url to the author or image place, max length = 100",
                                                max_length=100,
                                                required=False,
                                            ),
                                        ),
                                        (
                                            "license_type",
                                            wagtail.blocks.CharBlock(
                                                help_text="Optional. The type of license, eg: Creative Commons. max length = 50",
                                                max_length=50,
                                                required=False,
                                            ),
                                        ),
                                        (
                                            "license_url",
                                            wagtail.blocks.URLBlock(
                                                help_text="Optional. The link to relevant license. max length = 100",
                                                max_length=100,
                                                required=False,
                                            ),
                                        ),
                                    ]
                                ),
                            ),
                            (
                                "youtube",
                                wagtail.blocks.StructBlock(
                                    [
                                        (
                                            "src",
                                            wagtail.blocks.URLBlock(
                                                help_text="Get src from in the youtube embed code, include start if needed.",
                                                max_length=255,
                                                required=True,
                                            ),
                                        ),
                                        (
                                            "short",
                                            wagtail.blocks.BooleanBlock(
                                                help_text="Tick this box if the video is a short, i.e vertical format",
                                                required=False,
                                            ),
                                        ),
                                        (
                                            "limit",
                                            wagtail.blocks.BooleanBlock(
                                                help_text="Tick this box if you would like to limit recommended videos to this channel",
                                                required=False,
                                            ),
                                        ),
                                    ]
                                ),
                            ),
                        ],
                        null=True,
                    ),
                ),
                (
                    "banner_image",
                    models.ForeignKey(
                        help_text="Image size: 2048px x 1280px. Please optimize image size before uploading.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="wagtailimages.image",
                    ),
                ),
                (
                    "campaign",
                    models.OneToOneField(
                        help_text="The associated campaign. IMPORTANT. PLease make sure the title on this page is the same as the campaign name.",
                        on_delete=django.db.models.deletion.PROTECT,
                        to="campaigns.campaign",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
            bases=(wagtail_headless_preview.models.HeadlessMixin, "wagtailcore.page"),
        ),
    ]
