# Generated by Django 4.2.1 on 2024-12-25 06:38

from django.db import migrations
import streams.customblocks
import wagtail.blocks
import wagtail.fields


class Migration(migrations.Migration):
    dependencies = [
        ("campaigns", "0005_campaignimagebannerpage"),
    ]

    operations = [
        migrations.AlterField(
            model_name="campaignimagebannerpage",
            name="additional_details",
            field=wagtail.fields.StreamField(
                [
                    ("rich_text", streams.customblocks.CustomRichTextBlock()),
                    (
                        "text_width_img",
                        wagtail.blocks.StructBlock(
                            [
                                (
                                    "image",
                                    streams.customblocks.CustomImageChooserBlock(
                                        help_text="Required. Image size: 2048px x 1280px (16/10 ratio)",
                                        required=True,
                                    ),
                                ),
                                (
                                    "caption",
                                    wagtail.blocks.CharBlock(
                                        help_text="Optional. Caption, max length = 200",
                                        max_length=200,
                                        required=False,
                                    ),
                                ),
                                (
                                    "author",
                                    wagtail.blocks.CharBlock(
                                        help_text="Optional. The image creators name if attribution is required or nice to do, max length = 50",
                                        max_length=50,
                                        required=False,
                                    ),
                                ),
                                (
                                    "attribution_url",
                                    wagtail.blocks.URLBlock(
                                        help_text="Optional. The url to the author or image place, max length = 100",
                                        max_length=100,
                                        required=False,
                                    ),
                                ),
                                (
                                    "license_type",
                                    wagtail.blocks.CharBlock(
                                        help_text="Optional. The type of license, eg: Creative Commons. max length = 50",
                                        max_length=50,
                                        required=False,
                                    ),
                                ),
                                (
                                    "license_url",
                                    wagtail.blocks.URLBlock(
                                        help_text="Optional. The link to relevant license. max length = 100",
                                        max_length=100,
                                        required=False,
                                    ),
                                ),
                            ]
                        ),
                    ),
                    (
                        "youtube",
                        wagtail.blocks.StructBlock(
                            [
                                (
                                    "src",
                                    wagtail.blocks.URLBlock(
                                        help_text="Get src from in the youtube embed code, include start if needed.",
                                        max_length=255,
                                        required=True,
                                    ),
                                ),
                                (
                                    "short",
                                    wagtail.blocks.BooleanBlock(
                                        help_text="Tick this box if the video is a short, i.e vertical format",
                                        required=False,
                                    ),
                                ),
                                (
                                    "limit",
                                    wagtail.blocks.BooleanBlock(
                                        help_text="Tick this box if you would like to limit recommended videos to this channel",
                                        required=False,
                                    ),
                                ),
                            ]
                        ),
                    ),
                    (
                        "show_hide",
                        wagtail.blocks.StructBlock(
                            [
                                ("showing", wagtail.blocks.CharBlock(max_length=255)),
                                (
                                    "hidden",
                                    wagtail.blocks.RichTextBlock(
                                        features=["h4", "link", "ol", "ul"]
                                    ),
                                ),
                            ]
                        ),
                    ),
                ],
                null=True,
            ),
        ),
    ]
