# Generated by Django 4.2.1 on 2025-06-30 15:15

from decimal import Decimal
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("campaigns", "0006_alter_campaignimagebannerpage_additional_details"),
    ]

    operations = [
        migrations.AddField(
            model_name="campaign",
            name="note",
            field=models.TextField(
                blank=True,
                help_text="Notes regarding this campaign if any",
                verbose_name="Campaign Note",
            ),
        ),
        migrations.AddField(
            model_name="campaign",
            name="target_actual_difference",
            field=models.DecimalField(
                decimal_places=0,
                default=Decimal("0"),
                help_text="Non editable, auto calculated. Actual - Target",
                max_digits=10,
                verbose_name="actual vs target diff. (￥)",
            ),
        ),
        migrations.AddField(
            model_name="campaign",
            name="target_monthly_recurring_revenue_increase",
            field=models.DecimalField(
                decimal_places=0,
                default=Decimal("0"),
                help_text="Required. Complete 'Target Monthly Recurring Revenue Increase' before the campaign start date",
                max_digits=10,
                validators=[django.core.validators.MinValueValidator(Decimal("0"))],
                verbose_name="Target Rev Inc. (￥)",
            ),
        ),
        migrations.AddField(
            model_name="campaign",
            name="target_total_customer_increase",
            field=models.PositiveSmallIntegerField(
                default=0,
                help_text="Required. Complete 'Target Customer Increase' before the campaign start date",
                verbose_name="Target Cust. Inc.",
            ),
        ),
        migrations.AlterField(
            model_name="campaign",
            name="monthly_recurring_revenue_increase",
            field=models.DecimalField(
                decimal_places=0,
                default=Decimal("0"),
                help_text="Required. Complete 'Actual Monthly Recurring Revenue Increase' after the campaign ends",
                max_digits=10,
                validators=[django.core.validators.MinValueValidator(Decimal("0"))],
                verbose_name="Monthly Rec Rev Increase (￥)",
            ),
        ),
        migrations.AlterField(
            model_name="campaign",
            name="smart_goals_achieved",
            field=models.BooleanField(
                default=False,
                help_text="Required. Completed after campaign results finalized. Please consider 'M' in SMART to answer this question",
                verbose_name="Smart Goals Achieved",
            ),
        ),
        migrations.AlterField(
            model_name="campaign",
            name="total_customer_increase",
            field=models.PositiveSmallIntegerField(
                default=0,
                help_text="Required. Complete 'Actual Total Customer Increase' after the campaign ends",
                verbose_name="Total Cust. Inc.",
            ),
        ),
    ]
