# Generated by Django 4.2.1 on 2025-06-30 17:14

import campaigns.models
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("campaigns", "0007_campaign_note_campaign_target_actual_difference_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="campaign",
            name="marketing_start_date",
            field=models.DateField(
                default=campaigns.models.default_marketing_start,
                help_text="Required. This will determine the visibility of the campaign once the CMS page has been created",
                verbose_name="Start Date",
            ),
        ),
        migrations.AlterField(
            model_name="campaign",
            name="target_actual_difference",
            field=models.DecimalField(
                decimal_places=0,
                default=Decimal("0"),
                help_text="Non editable, auto calculated. Actual - Target Revenue Increase",
                max_digits=10,
                verbose_name="rev: actual vs target diff.(￥)",
            ),
        ),
    ]
