# Generated by Django 4.2.1 on 2025-06-30 17:38

from decimal import Decimal
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("campaigns", "0008_campaign_marketing_start_date_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="campaign",
            name="target_actual_difference",
        ),
        migrations.AlterField(
            model_name="campaign",
            name="monthly_recurring_revenue_increase",
            field=models.DecimalField(
                decimal_places=0,
                default=Decimal("0"),
                help_text="Required. Update 'Actual Monthly Recurring Revenue Increase' as results come in",
                max_digits=10,
                validators=[django.core.validators.MinValueValidator(Decimal("0"))],
                verbose_name="Monthly Rec Rev Increase (￥)",
            ),
        ),
        migrations.AlterField(
            model_name="campaign",
            name="total_customer_increase",
            field=models.PositiveSmallIntegerField(
                default=0,
                help_text="Required. Update 'Actual Total Customer Increase' as results appear",
                verbose_name="Total Cust. Inc.",
            ),
        ),
    ]
