# Generated by Django 4.2.1 on 2025-07-03 09:59

import campaigns.models
import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("campaigns", "0009_remove_campaign_target_actual_difference_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="campaignsimplebannerpage",
            name="marketing_start_date",
            field=models.DateField(
                blank=True,
                default=datetime.date(2020, 1, 1),
                help_text="Read only field that gets value from 'campaign'",
                verbose_name="Marketing Start Date",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="campaign",
            name="marketing_start_date",
            field=models.DateField(
                default=campaigns.models.default_marketing_start,
                help_text="Required. This will determine the visibility of the campaign once the CMS page has been created",
                verbose_name="Marketing Start Date",
            ),
        ),
    ]
