# Generated by Django 4.2.1 on 2025-07-03 14:04

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("campaigns", "0010_campaignsimplebannerpage_marketing_start_date_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="campaignimagebannerpage",
            name="marketing_start_date",
            field=models.DateField(
                blank=True,
                default=datetime.date(2020, 1, 1),
                help_text="Read only field that gets value from 'campaign'. Will determine when the page is visible on the home page and other places on site",
                verbose_name="Marketing Start Date",
            ),
            preserve_default=False,
        ),
    ]
