# Generated by Django 4.2.1 on 2024-03-05 08:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("languageschools", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="languageschoollistpage",
            name="display_title",
            field=models.CharField(
                help_text="Required. Max length 15 characters. Japanese",
                max_length=15,
                verbose_name="Display Title",
            ),
        ),
    ]
