# Generated by Django 4.2.1 on 2024-03-11 17:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("languageschools", "0003_languageschooldetailpage_display_city_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="languageschooldetailpage",
            name="display_tagline",
            field=models.CharField(
                default="Please add",
                help_text="Required. Max 50. Attractive, short summary of school",
                max_length=50,
                verbose_name="Display tagline",
            ),
            preserve_default=False,
        ),
    ]
