# Generated by Django 4.2.1 on 2024-03-13 04:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("languageschools", "0004_languageschooldetailpage_display_tagline"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="languageschooldetailpage",
            name="access_info",
        ),
        migrations.AddField(
            model_name="languageschooldetailpage",
            name="access_car",
            field=models.CharField(
                default="Please add",
                help_text="Required. Max 35char. Please explain in Japanese car access and whether parking is available or not",
                max_length=35,
                verbose_name="Access - Car",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="languageschooldetailpage",
            name="access_train",
            field=models.CharField(
                default="Please add",
                help_text="Required. Max 35char. Please explain in Japanese train access",
                max_length=35,
                verbose_name="Access - Train",
            ),
            preserve_default=False,
        ),
    ]
