# Generated by Django 4.2.1 on 2023-10-18 13:17

from django.db import migrations, models
import django.db.models.deletion
import wagtail_headless_preview.models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("wagtailcore", "0091_alter_page_title"),
    ]

    operations = [
        migrations.CreateModel(
            name="TestimonialListPage",
            fields=[
                (
                    "page_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="wagtailcore.page",
                    ),
                ),
                (
                    "display_title",
                    models.CharField(
                        help_text="Required. Max length 30 characters.",
                        max_length=15,
                        verbose_name="Display Title",
                    ),
                ),
                (
                    "tagline",
                    models.CharField(
                        help_text="Required. Max length 90 characters.",
                        max_length=90,
                        verbose_name="Tagline",
                    ),
                ),
            ],
            options={
                "verbose_name": "Testimonial list page",
            },
            bases=(wagtail_headless_preview.models.HeadlessMixin, "wagtailcore.page"),
        ),
    ]
