# Generated by Django 4.2.1 on 2023-10-19 04:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("testimonials", "0002_testimonialdetailpage"),
    ]

    operations = [
        migrations.AlterField(
            model_name="testimonialdetailpage",
            name="comment",
            field=models.TextField(
                blank=True,
                help_text="Required. Max length 300 chars. A short comment about the school to display in places on site.",
                max_length=300,
                verbose_name="Short Comment",
            ),
        ),
    ]
