# Generated by Django 4.2.1 on 2023-10-19 08:01

from django.db import migrations
import wagtail.blocks
import wagtail.fields


class Migration(migrations.Migration):
    dependencies = [
        ("testimonials", "0003_alter_testimonialdetailpage_comment"),
    ]

    operations = [
        migrations.AlterField(
            model_name="testimonialdetailpage",
            name="customer_interview",
            field=wagtail.fields.StreamField(
                [
                    (
                        "youtube",
                        wagtail.blocks.StructBlock(
                            [
                                (
                                    "src",
                                    wagtail.blocks.URLBlock(
                                        help_text="Get src from in the youtube embed code, include start if needed.",
                                        max_length=255,
                                        required=True,
                                    ),
                                ),
                                (
                                    "short",
                                    wagtail.blocks.BooleanBlock(
                                        help_text="Tick this box if the video is a short, i.e vertical format",
                                        required=False,
                                    ),
                                ),
                                (
                                    "limit",
                                    wagtail.blocks.BooleanBlock(
                                        help_text="Tick this box if you would like to limit recommended videos to this channel",
                                        required=False,
                                    ),
                                ),
                            ]
                        ),
                    ),
                    (
                        "conversation",
                        wagtail.blocks.StructBlock(
                            [
                                (
                                    "title",
                                    wagtail.blocks.CharBlock(
                                        help_text="A short title for the conversation. Max 50 chars",
                                        max_length=50,
                                    ),
                                ),
                                (
                                    "intro",
                                    wagtail.blocks.TextBlock(
                                        help_text="Set the scene of the conversation"
                                    ),
                                ),
                                (
                                    "person_one_name",
                                    wagtail.blocks.CharBlock(
                                        help_text="First person in conversation name, correlates to person one in following blocks. Please use names starting with different letters. Eg. Bob for first person and Sarah for second person. B and S in this example",
                                        max_length=10,
                                    ),
                                ),
                                (
                                    "person_two_name",
                                    wagtail.blocks.CharBlock(
                                        help_text="Secon person in conversation name, correlates to person two in following blocks.",
                                        max_length=10,
                                    ),
                                ),
                                (
                                    "conversation",
                                    wagtail.blocks.ListBlock(
                                        wagtail.blocks.StructBlock(
                                            [
                                                (
                                                    "person_one",
                                                    wagtail.blocks.CharBlock(
                                                        max_length=255
                                                    ),
                                                ),
                                                (
                                                    "person_two",
                                                    wagtail.blocks.CharBlock(
                                                        max_length=255
                                                    ),
                                                ),
                                            ]
                                        )
                                    ),
                                ),
                            ]
                        ),
                    ),
                ],
                null=True,
                use_json_field=True,
            ),
        ),
    ]
