# Generated by Django 4.2.1 on 2024-01-19 10:47

from django.db import migrations, models
import django.db.models.deletion
import wagtail.fields


class Migration(migrations.Migration):
    dependencies = [
        ("wagtailimages", "0025_alter_image_file_alter_rendition_file"),
        ("testimonials", "0005_alter_testimonialdetailpage_customer_interview"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="testimonialdetailpage",
            name="customer_image",
        ),
        migrations.AddField(
            model_name="testimonialdetailpage",
            name="customer_portrait_image",
            field=models.ForeignKey(
                help_text="Image size: 1400 x 1800px (7:9). Please optimize image size before uploading.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="wagtailimages.image",
            ),
        ),
        migrations.AddField(
            model_name="testimonialdetailpage",
            name="customer_square_image",
            field=models.ForeignKey(
                help_text="Image size: 1080px x 1080px (1:1). Please optimize image size before uploading.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="wagtailimages.image",
            ),
        ),
        migrations.AddField(
            model_name="testimonialdetailpage",
            name="lead_sentence",
            field=models.CharField(
                blank=True,
                help_text="Required. 30char max. One small sentence to describe their feeling about the company",
                max_length=30,
                verbose_name="Lead Sentence",
            ),
        ),
        migrations.AlterField(
            model_name="testimonialdetailpage",
            name="comment",
            field=wagtail.fields.RichTextField(
                help_text="Required. Max length 300 chars. A short comment about the company to display in places on site.",
                max_length=300,
                verbose_name="Short Comment",
            ),
        ),
        migrations.AlterField(
            model_name="testimonialdetailpage",
            name="occupation",
            field=models.CharField(
                blank=True,
                help_text="Not required. Max length 100 chars",
                max_length=100,
                verbose_name="Occupation of customer",
            ),
        ),
    ]
