# Generated by Django 4.2.1 on 2024-07-21 13:58

from django.db import migrations
import wagtail.fields


class Migration(migrations.Migration):
    dependencies = [
        ("testimonials", "0006_remove_testimonialdetailpage_customer_image_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="testimonialdetailpage",
            name="comment",
            field=wagtail.fields.RichTextField(
                help_text="Required. Max length 320 chars. A short comment about the company to display in places on site.",
                max_length=320,
                verbose_name="Short Comment",
            ),
        ),
    ]
