# Generated by Django 4.2.1 on 2023-10-10 08:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("schedules", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="supersassschedule",
            name="slug",
            field=models.SlugField(
                editable=False,
                help_text="AUTOGENERATED. Please DO NOT modify this value",
                max_length=100,
                unique=True,
            ),
        ),
    ]
