# Generated by Django 4.2.1 on 2023-10-10 13:47

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("languageschools", "0001_initial"),
        ("schedules", "0003_alter_supersassschedule_slug"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="SuperSassSchedule",
            new_name="SuperSaasSchedule",
        ),
    ]
