# Generated by Django 4.2.1 on 2023-07-03 13:18

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import wagtail_headless_preview.models


class Migration(migrations.Migration):
    dependencies = [
        ("wagtailimages", "0025_alter_image_file_alter_rendition_file"),
        ("wagtailcore", "0083_workflowcontenttype"),
        ("lessons", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="LessonDetailPage",
            fields=[
                (
                    "page_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="wagtailcore.page",
                    ),
                ),
                (
                    "jp_title",
                    models.CharField(
                        help_text="Required. Max length 70 characters, 60 or less is ideal",
                        max_length=70,
                        verbose_name="Japanese Title",
                    ),
                ),
                (
                    "published_date",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        help_text="IMPORTANT NOTE: This date will affect the order on list pages.",
                    ),
                ),
                (
                    "header_image",
                    models.ForeignKey(
                        help_text="Image size: 2048px x 1280px",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="wagtailimages.image",
                    ),
                ),
            ],
            options={
                "verbose_name": "Blog Post",
                "verbose_name_plural": "Blog Posts",
                "ordering": ["-published_date"],
            },
            bases=(wagtail_headless_preview.models.HeadlessMixin, "wagtailcore.page"),
        ),
    ]
