# Generated by Django 4.2.1 on 2023-07-04 08:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("lessons", "0002_lessondetailpage"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="lessondetailpage",
            options={
                "ordering": ["-published_date"],
                "verbose_name": "Lesson Detail Page",
                "verbose_name_plural": "Lesson Detail Pages",
            },
        ),
        migrations.AddField(
            model_name="lessondetailpage",
            name="estimated_time",
            field=models.PositiveSmallIntegerField(
                default=1, help_text="Estimated time to complete this lesson"
            ),
            preserve_default=False,
        ),
    ]
