# Generated by Django 4.2.1 on 2023-07-04 08:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("wagtailimages", "0025_alter_image_file_alter_rendition_file"),
        ("lessons", "0003_alter_lessondetailpage_options_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="LessonCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="English name for category, max 30 chars.",
                        max_length=30,
                        verbose_name="Category name",
                    ),
                ),
                (
                    "ja_name",
                    models.CharField(
                        help_text="English name for category, max 30 chars.",
                        max_length=30,
                        verbose_name="Japanese Category name",
                    ),
                ),
                (
                    "slug",
                    models.SlugField(
                        help_text="Use English name to create a slug with only hypens and lowercase letters",
                        max_length=40,
                        unique=True,
                    ),
                ),
            ],
            options={
                "verbose_name": "Lesson Category",
                "verbose_name_plural": "Lesson Categories",
            },
        ),
        migrations.AlterField(
            model_name="lessondetailpage",
            name="header_image",
            field=models.ForeignKey(
                help_text="Image size: 2048px x 1280px. Please optimize image size before uploading.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="wagtailimages.image",
            ),
        ),
    ]
