# Generated by Django 4.2.1 on 2023-07-04 09:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("lessons", "0004_lessoncategory_alter_lessondetailpage_header_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="lessondetailpage",
            name="category",
            field=models.ForeignKey(
                help_text="Please categorize the lesson",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="lessons.lessoncategory",
            ),
        ),
    ]
