# Generated by Django 4.2.1 on 2023-07-05 08:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("lessons", "0005_lessondetailpage_category"),
    ]

    operations = [
        migrations.RenameField(
            model_name="lessondetailpage",
            old_name="jp_title",
            new_name="ja_title",
        ),
        migrations.AddField(
            model_name="lessondetailpage",
            name="short_intro",
            field=models.CharField(
                default="Short intro here --> ",
                help_text="A catchy, oneline introduction of what the lesson is about. Max length 140 chars",
                max_length=70,
                verbose_name="Short Intro",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="lessondetailpage",
            name="estimated_time",
            field=models.PositiveSmallIntegerField(
                help_text="Estimated time in minutes to complete this lesson"
            ),
        ),
    ]
