# Generated by Django 4.2.1 on 2023-07-05 08:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("lessons", "0006_rename_jp_title_lessondetailpage_ja_title_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="lessonlistpage",
            name="jp_title",
        ),
        migrations.AddField(
            model_name="lessonlistpage",
            name="ja_title",
            field=models.CharField(
                default="",
                help_text="Required. Max length 15 characters.",
                max_length=15,
                verbose_name="Japanese Title",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="lessonlistpage",
            name="short_intro",
            field=models.CharField(
                default="A lesson intro here please",
                help_text="An introduction to the free lessons concept. max length 90 chars",
                max_length=90,
                verbose_name="Short Intro",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="lessondetailpage",
            name="ja_title",
            field=models.CharField(
                help_text="Required. Max length 50 characters, 45 or less is ideal",
                max_length=50,
                verbose_name="Japanese Title",
            ),
        ),
        migrations.AlterField(
            model_name="lessondetailpage",
            name="short_intro",
            field=models.CharField(
                help_text="A catchy, oneline introduction of what the lesson is about. Max length 90 chars",
                max_length=90,
                verbose_name="Short Intro",
            ),
        ),
    ]
