# Generated by Django 4.2.1 on 2023-07-05 14:21

from django.db import migrations, models
import streams.customblocks
import wagtail.blocks
import wagtail.fields


class Migration(migrations.Migration):
    dependencies = [
        ("lessons", "0008_alter_lessonlistpage_short_intro"),
    ]

    operations = [
        migrations.AddField(
            model_name="lessondetailpage",
            name="blog_content",
            field=wagtail.fields.StreamField(
                [
                    ("rich_text", streams.customblocks.CustomRichTextBlock()),
                    (
                        "block_quote",
                        wagtail.blocks.StructBlock(
                            [
                                (
                                    "author",
                                    wagtail.blocks.CharBlock(
                                        help_text="The quote author's full name",
                                        max_length=40,
                                        required=True,
                                    ),
                                ),
                                (
                                    "quote",
                                    wagtail.blocks.TextBlock(
                                        help_text="The quote itself", required=True
                                    ),
                                ),
                                (
                                    "citation_url",
                                    wagtail.blocks.URLBlock(
                                        help_text="Link url from where quotation comes from, if available",
                                        required=False,
                                    ),
                                ),
                                (
                                    "citation_source",
                                    wagtail.blocks.CharBlock(
                                        help_text=" The title of the creative work from which the quote comes",
                                        max_length=40,
                                        required=True,
                                    ),
                                ),
                            ]
                        ),
                    ),
                    (
                        "full_width_img",
                        wagtail.blocks.StructBlock(
                            [
                                (
                                    "image",
                                    streams.customblocks.CustomImageChooserBlock(
                                        help_text="Full width at large screen size. Use an image NOTE: TO BE DECIDED***",
                                        required=True,
                                    ),
                                ),
                                (
                                    "caption",
                                    wagtail.blocks.CharBlock(
                                        help_text="Optional. Caption, max length = 200",
                                        max_length=200,
                                        required=False,
                                    ),
                                ),
                                (
                                    "author",
                                    wagtail.blocks.CharBlock(
                                        help_text="Optional. The image creators name if attribution is required or nice to do, max length = 50",
                                        max_length=50,
                                        required=False,
                                    ),
                                ),
                                (
                                    "attribution_url",
                                    wagtail.blocks.URLBlock(
                                        help_text="Optional. The url to the author or image place, max length = 100",
                                        max_length=100,
                                        required=False,
                                    ),
                                ),
                                (
                                    "license_type",
                                    wagtail.blocks.CharBlock(
                                        help_text="Optional. The type of license, eg: Creative Commons. max length = 50",
                                        max_length=50,
                                        required=False,
                                    ),
                                ),
                                (
                                    "license_url",
                                    wagtail.blocks.URLBlock(
                                        help_text="Optional. The link to relevant license. max length = 100",
                                        max_length=100,
                                        required=False,
                                    ),
                                ),
                            ]
                        ),
                    ),
                    (
                        "beyond_text_img",
                        wagtail.blocks.StructBlock(
                            [
                                (
                                    "image",
                                    streams.customblocks.CustomImageChooserBlock(
                                        help_text="Image will extend beyond text content width at large screen size. Use an image **TO BE DECIDED***",
                                        required=True,
                                    ),
                                ),
                                (
                                    "caption",
                                    wagtail.blocks.CharBlock(
                                        help_text="Optional. Caption, max length = 200",
                                        max_length=200,
                                        required=False,
                                    ),
                                ),
                                (
                                    "author",
                                    wagtail.blocks.CharBlock(
                                        help_text="Optional. The image creators name if attribution is required or nice to do, max length = 50",
                                        max_length=50,
                                        required=False,
                                    ),
                                ),
                                (
                                    "attribution_url",
                                    wagtail.blocks.URLBlock(
                                        help_text="Optional. The url to the author or image place, max length = 100",
                                        max_length=100,
                                        required=False,
                                    ),
                                ),
                                (
                                    "license_type",
                                    wagtail.blocks.CharBlock(
                                        help_text="Optional. The type of license, eg: Creative Commons. max length = 50",
                                        max_length=50,
                                        required=False,
                                    ),
                                ),
                                (
                                    "license_url",
                                    wagtail.blocks.URLBlock(
                                        help_text="Optional. The link to relevant license. max length = 100",
                                        max_length=100,
                                        required=False,
                                    ),
                                ),
                            ]
                        ),
                    ),
                    (
                        "text_width_img",
                        wagtail.blocks.StructBlock(
                            [
                                (
                                    "image",
                                    streams.customblocks.CustomImageChooserBlock(
                                        help_text="Image will extend beyond text content width at large screen size. Use an image **TO BE DECIDED***",
                                        required=True,
                                    ),
                                ),
                                (
                                    "caption",
                                    wagtail.blocks.CharBlock(
                                        help_text="Optional. Caption, max length = 200",
                                        max_length=200,
                                        required=False,
                                    ),
                                ),
                                (
                                    "author",
                                    wagtail.blocks.CharBlock(
                                        help_text="Optional. The image creators name if attribution is required or nice to do, max length = 50",
                                        max_length=50,
                                        required=False,
                                    ),
                                ),
                                (
                                    "attribution_url",
                                    wagtail.blocks.URLBlock(
                                        help_text="Optional.  The url to the author or image place, max length = 100",
                                        max_length=100,
                                        required=False,
                                    ),
                                ),
                                (
                                    "license_type",
                                    wagtail.blocks.CharBlock(
                                        help_text="Optional. The type of license, eg: Creative Commons. max length = 50",
                                        max_length=50,
                                        required=False,
                                    ),
                                ),
                                (
                                    "license_url",
                                    wagtail.blocks.URLBlock(
                                        help_text="Optional. The link to relevant license. max length = 100",
                                        max_length=100,
                                        required=False,
                                    ),
                                ),
                            ]
                        ),
                    ),
                ],
                null=True,
                use_json_field=True,
            ),
        ),
        migrations.AlterField(
            model_name="lessonlistpage",
            name="short_intro",
            field=models.CharField(
                help_text="An introduction to the free lessons concept. max length 160 chars",
                max_length=160,
                verbose_name="Short Intro",
            ),
        ),
    ]
