# Generated by Django 4.2.1 on 2023-07-05 14:26

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("lessons", "0009_lessondetailpage_blog_content_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="lessondetailpage",
            old_name="blog_content",
            new_name="lesson_content",
        ),
    ]
