# Generated by Django 4.2.1 on 2023-08-04 08:24

from django.db import migrations
import streams.customblocks
import wagtail.blocks
import wagtail.fields


class Migration(migrations.Migration):
    dependencies = [
        ("lessons", "0020_relatedlessons_delete_lessonrelatedlessons"),
    ]

    operations = [
        migrations.AlterField(
            model_name="lessondetailpage",
            name="lesson_content",
            field=wagtail.fields.StreamField(
                [
                    ("rich_text", streams.customblocks.CustomRichTextBlock()),
                    (
                        "block_quote",
                        wagtail.blocks.StructBlock(
                            [
                                (
                                    "author",
                                    wagtail.blocks.CharBlock(
                                        help_text="The quote author's full name",
                                        max_length=40,
                                        required=True,
                                    ),
                                ),
                                (
                                    "quote",
                                    wagtail.blocks.TextBlock(
                                        help_text="The quote itself", required=True
                                    ),
                                ),
                                (
                                    "citation_url",
                                    wagtail.blocks.URLBlock(
                                        help_text="Link url from where quotation comes from, if available",
                                        required=False,
                                    ),
                                ),
                                (
                                    "citation_source",
                                    wagtail.blocks.CharBlock(
                                        help_text=" The title of the creative work from which the quote comes",
                                        max_length=40,
                                        required=True,
                                    ),
                                ),
                            ]
                        ),
                    ),
                    (
                        "full_width_img",
                        wagtail.blocks.StructBlock(
                            [
                                (
                                    "image",
                                    streams.customblocks.CustomImageChooserBlock(
                                        help_text="Full width at large screen size. Image size: 2048px x 1280px (16/10 ratio)",
                                        required=True,
                                    ),
                                ),
                                (
                                    "caption",
                                    wagtail.blocks.CharBlock(
                                        help_text="Optional. Caption, max length = 200",
                                        max_length=200,
                                        required=False,
                                    ),
                                ),
                                (
                                    "author",
                                    wagtail.blocks.CharBlock(
                                        help_text="Optional. The image creators name if attribution is required or nice to do, max length = 50",
                                        max_length=50,
                                        required=False,
                                    ),
                                ),
                                (
                                    "attribution_url",
                                    wagtail.blocks.URLBlock(
                                        help_text="Optional. The url to the author or image place, max length = 100",
                                        max_length=100,
                                        required=False,
                                    ),
                                ),
                                (
                                    "license_type",
                                    wagtail.blocks.CharBlock(
                                        help_text="Optional. The type of license, eg: Creative Commons. max length = 50",
                                        max_length=50,
                                        required=False,
                                    ),
                                ),
                                (
                                    "license_url",
                                    wagtail.blocks.URLBlock(
                                        help_text="Optional. The link to relevant license. max length = 100",
                                        max_length=100,
                                        required=False,
                                    ),
                                ),
                            ]
                        ),
                    ),
                    (
                        "beyond_text_img",
                        wagtail.blocks.StructBlock(
                            [
                                (
                                    "image",
                                    streams.customblocks.CustomImageChooserBlock(
                                        help_text="Image will extend beyond text content width at large screen size. Image size: 2048px x 1280px (16/10 ratio)",
                                        required=True,
                                    ),
                                ),
                                (
                                    "caption",
                                    wagtail.blocks.CharBlock(
                                        help_text="Optional. Caption, max length = 200",
                                        max_length=200,
                                        required=False,
                                    ),
                                ),
                                (
                                    "author",
                                    wagtail.blocks.CharBlock(
                                        help_text="Optional. The image creators name if attribution is required or nice to do, max length = 50",
                                        max_length=50,
                                        required=False,
                                    ),
                                ),
                                (
                                    "attribution_url",
                                    wagtail.blocks.URLBlock(
                                        help_text="Optional. The url to the author or image place, max length = 100",
                                        max_length=100,
                                        required=False,
                                    ),
                                ),
                                (
                                    "license_type",
                                    wagtail.blocks.CharBlock(
                                        help_text="Optional. The type of license, eg: Creative Commons. max length = 50",
                                        max_length=50,
                                        required=False,
                                    ),
                                ),
                                (
                                    "license_url",
                                    wagtail.blocks.URLBlock(
                                        help_text="Optional. The link to relevant license. max length = 100",
                                        max_length=100,
                                        required=False,
                                    ),
                                ),
                            ]
                        ),
                    ),
                    (
                        "text_width_img",
                        wagtail.blocks.StructBlock(
                            [
                                (
                                    "image",
                                    streams.customblocks.CustomImageChooserBlock(
                                        help_text="Image will extend beyond text content width at large screen size. Image size: 2048px x 1280px (16/10 ratio)  ",
                                        required=True,
                                    ),
                                ),
                                (
                                    "caption",
                                    wagtail.blocks.CharBlock(
                                        help_text="Optional. Caption, max length = 200",
                                        max_length=200,
                                        required=False,
                                    ),
                                ),
                                (
                                    "author",
                                    wagtail.blocks.CharBlock(
                                        help_text="Optional. The image creators name if attribution is required or nice to do, max length = 50",
                                        max_length=50,
                                        required=False,
                                    ),
                                ),
                                (
                                    "attribution_url",
                                    wagtail.blocks.URLBlock(
                                        help_text="Optional.  The url to the author or image place, max length = 100",
                                        max_length=100,
                                        required=False,
                                    ),
                                ),
                                (
                                    "license_type",
                                    wagtail.blocks.CharBlock(
                                        help_text="Optional. The type of license, eg: Creative Commons. max length = 50",
                                        max_length=50,
                                        required=False,
                                    ),
                                ),
                                (
                                    "license_url",
                                    wagtail.blocks.URLBlock(
                                        help_text="Optional. The link to relevant license. max length = 100",
                                        max_length=100,
                                        required=False,
                                    ),
                                ),
                            ]
                        ),
                    ),
                    (
                        "youtube",
                        wagtail.blocks.StructBlock(
                            [
                                (
                                    "src",
                                    wagtail.blocks.URLBlock(
                                        help_text="Get src from in the youtube embed code, include start if needed.",
                                        max_length=255,
                                        required=True,
                                    ),
                                ),
                                (
                                    "short",
                                    wagtail.blocks.BooleanBlock(
                                        help_text="Tick this box if the video is a short, i.e vertical format",
                                        required=False,
                                    ),
                                ),
                                (
                                    "limit",
                                    wagtail.blocks.BooleanBlock(
                                        help_text="Tick this box if you would like to limit recommended videos to this channel",
                                        required=False,
                                    ),
                                ),
                            ]
                        ),
                    ),
                    (
                        "conversation",
                        wagtail.blocks.StructBlock(
                            [
                                (
                                    "title",
                                    wagtail.blocks.CharBlock(
                                        help_text="A short title for the conversation. Max 30 chars",
                                        max_length=30,
                                    ),
                                ),
                                (
                                    "intro",
                                    wagtail.blocks.TextBlock(
                                        help_text="Set the scene of the conversation"
                                    ),
                                ),
                                (
                                    "person_one_name",
                                    wagtail.blocks.CharBlock(
                                        help_text="First person in conversation name, correlates to person one in following blocks. Please use names starting with different letters. Eg. Bob for first person and Sarah for second person. B and S in this example",
                                        max_length=10,
                                    ),
                                ),
                                (
                                    "person_two_name",
                                    wagtail.blocks.CharBlock(
                                        help_text="Secon person in conversation name, correlates to person two in following blocks.",
                                        max_length=10,
                                    ),
                                ),
                                (
                                    "conversation",
                                    wagtail.blocks.ListBlock(
                                        wagtail.blocks.StructBlock(
                                            [
                                                (
                                                    "person_one",
                                                    wagtail.blocks.CharBlock(
                                                        max_length=255
                                                    ),
                                                ),
                                                (
                                                    "person_two",
                                                    wagtail.blocks.CharBlock(
                                                        max_length=255
                                                    ),
                                                ),
                                            ]
                                        )
                                    ),
                                ),
                            ]
                        ),
                    ),
                    (
                        "mc_questions",
                        wagtail.blocks.StructBlock(
                            [
                                (
                                    "title",
                                    wagtail.blocks.CharBlock(
                                        help_text="A short title for the series of multiple choice questions. Max 30 chars",
                                        max_length=30,
                                    ),
                                ),
                                (
                                    "intro",
                                    wagtail.blocks.TextBlock(
                                        help_text="More information, if required about the test series. Not required",
                                        required=False,
                                    ),
                                ),
                                (
                                    "questions",
                                    wagtail.blocks.ListBlock(
                                        wagtail.blocks.StructBlock(
                                            [
                                                (
                                                    "question",
                                                    wagtail.blocks.CharBlock(
                                                        max_length=255
                                                    ),
                                                ),
                                                (
                                                    "correct_answer",
                                                    wagtail.blocks.CharBlock(
                                                        max_length=50
                                                    ),
                                                ),
                                                (
                                                    "incorrect_answer1",
                                                    wagtail.blocks.CharBlock(
                                                        max_length=50
                                                    ),
                                                ),
                                                (
                                                    "incorrect_answer2",
                                                    wagtail.blocks.CharBlock(
                                                        max_length=50
                                                    ),
                                                ),
                                            ]
                                        )
                                    ),
                                ),
                            ]
                        ),
                    ),
                ],
                null=True,
                use_json_field=True,
            ),
        ),
    ]
