# Generated by Django 4.2.1 on 2023-08-17 07:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("staff", "0007_staffdetailpage_hobbies_staffdetailpage_role_and_more"),
        ("lessons", "0021_alter_lessondetailpage_lesson_content"),
    ]

    operations = [
        migrations.AddField(
            model_name="lessondetailpage",
            name="author",
            field=models.ForeignKey(
                help_text="Author of this lesson",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="lessons",
                to="staff.staffdetailpage",
            ),
        ),
    ]
