# Generated by Django 4.2.1 on 2023-11-24 10:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("lessons", "0024_alter_lessondetailpage_lesson_content"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="lessonlistpage",
            options={
                "verbose_name": "Blog Lessons List Page",
                "verbose_name_plural": "Blog Lessons List Pages",
            },
        ),
        migrations.RemoveField(
            model_name="lessondetailpage",
            name="ja_title",
        ),
        migrations.RemoveField(
            model_name="lessondetailpage",
            name="short_intro",
        ),
        migrations.RemoveField(
            model_name="lessonlistpage",
            name="ja_title",
        ),
        migrations.RemoveField(
            model_name="lessonlistpage",
            name="short_intro",
        ),
        migrations.AddField(
            model_name="lessondetailpage",
            name="display_tagline",
            field=models.CharField(
                default="Please add something",
                help_text="A catchy, short introduction of what the blog lesson is about. Max length 160 chars",
                max_length=160,
                verbose_name="Display Tagline",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="lessondetailpage",
            name="display_title",
            field=models.CharField(
                default="Please add something",
                help_text="Required. Max length 100 characters, 45 or less is ideal",
                max_length=100,
                verbose_name="Display Title",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="lessonlistpage",
            name="display_tagline",
            field=models.CharField(
                default="Please add something",
                help_text="Required. Max length 160 char. A catchy, attractive tagline to give more information and sell the blog lessons",
                max_length=160,
                verbose_name="Display Tagline",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="lessonlistpage",
            name="display_title",
            field=models.CharField(
                default="Please",
                help_text="Required. Max length 15 characters.",
                max_length=15,
                verbose_name="Display Title",
            ),
            preserve_default=False,
        ),
    ]
