# Generated by Django 4.2.1 on 2023-11-24 10:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("lessons", "0025_alter_lessonlistpage_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="lessoncategory",
            name="ja_name",
            field=models.CharField(
                help_text="English name for category, max 30 chars.",
                max_length=30,
                unique=True,
                verbose_name="Japanese Category name",
            ),
        ),
        migrations.AlterField(
            model_name="lessoncategory",
            name="name",
            field=models.CharField(
                help_text="English name for category, max 30 chars.",
                max_length=30,
                unique=True,
                verbose_name="Category name",
            ),
        ),
    ]
