# Generated by Django 4.2.1 on 2023-11-24 10:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("lessons", "0026_alter_lessoncategory_ja_name_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="lessonlistpage",
            name="display_title",
            field=models.CharField(
                help_text="Required. Max length 15 characters.",
                max_length=100,
                verbose_name="Display Title",
            ),
        ),
    ]
