# Generated by Django 4.2.1 on 2023-12-11 05:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("lessons", "0029_alter_lessondetailpage_lesson_content"),
    ]

    operations = [
        migrations.AlterField(
            model_name="lessondetailpage",
            name="display_tagline",
            field=models.CharField(
                help_text="A catchy, short introduction of what the blog lesson is about. Max length 50 chars",
                max_length=50,
                verbose_name="Display Tagline",
            ),
        ),
    ]
