# Generated by Django 4.2.1 on 2024-06-26 08:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("lessons", "0031_remove_lessonlistpage_display_tagline"),
    ]

    operations = [
        migrations.AlterField(
            model_name="lessondetailpage",
            name="display_tagline",
            field=models.CharField(
                help_text="A catchy, short introduction of what the blog lesson is about. Max length 200 chars",
                max_length=200,
                verbose_name="Display Tagline",
            ),
        ),
    ]
