# Generated by Django 4.2.1 on 2023-10-23 08:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="ptype",
            field=models.PositiveSmallIntegerField(
                choices=[(0, "Class"), (1, "Learning Experience"), (2, "Book")],
                default=1,
                help_text="Required",
                verbose_name="Product Type",
            ),
            preserve_default=False,
        ),
    ]
