# Generated by Django 4.2.1 on 2023-10-23 08:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0002_product_ptype"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="ptype",
            field=models.CharField(
                choices=[
                    ("class", "Class"),
                    ("experience", "Learning Experience"),
                    ("book", "Book"),
                ],
                help_text="Required",
                verbose_name="Product Type",
            ),
        ),
    ]
