# Generated by Django 4.2.1 on 2023-10-23 09:16

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0003_alter_product_ptype"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Product",
            new_name="ProductService",
        ),
    ]
