# Generated by Django 4.2.1 on 2023-10-23 09:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0004_rename_product_productservice"),
    ]

    operations = [
        migrations.AddField(
            model_name="productservice",
            name="service_or_product",
            field=models.CharField(
                choices=[("service", "Service"), ("product", "Product")],
                default="service",
                help_text="Required",
                verbose_name="Service or Product",
            ),
            preserve_default=False,
        ),
    ]
