# Generated by Django 4.2.1 on 2023-10-23 14:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0005_productservice_service_or_product"),
    ]

    operations = [
        migrations.AddField(
            model_name="productservice",
            name="description",
            field=models.TextField(
                default="Fill in please",
                help_text="Required. Base description of product. Any changes here should be reflected in any display page or language",
                verbose_name="Product Description",
            ),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name="ProductServicePrice",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    models.DateTimeField(auto_now_add=True, verbose_name="created"),
                ),
                (
                    "modified",
                    models.DateTimeField(auto_now=True, verbose_name="modified"),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Required. Max length 200 characters.",
                        max_length=200,
                        verbose_name="Name",
                    ),
                ),
                (
                    "price",
                    models.DecimalField(
                        decimal_places=0,
                        help_text="Required. Pretax selling price in Japanese yen. Max digits - 10",
                        max_digits=10,
                        verbose_name="Price",
                    ),
                ),
                (
                    "start_date",
                    models.DateTimeField(
                        help_text="Required. Please make sure to set this. It is generally never changed",
                        verbose_name="Start date",
                    ),
                ),
                (
                    "end_date",
                    models.DateTimeField(
                        blank=True,
                        help_text="NOT Required. Important ** Do not set this for long term prices. It is only used to have a short sale price or to terminate a long term price. It will remove the price from any public display",
                        null=True,
                        verbose_name="Start date",
                    ),
                ),
                (
                    "product_service",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="prices",
                        to="products.productservice",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
