# Generated by Django 4.2.1 on 2023-10-23 15:06

from decimal import Decimal
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0006_productservice_description_productserviceprice"),
    ]

    operations = [
        migrations.AlterField(
            model_name="productserviceprice",
            name="end_date",
            field=models.DateTimeField(
                blank=True,
                help_text="NOT Required. Important ** Do not set this for long term prices. It is only used to have a short sale price or to terminate a long term price. It will remove the price from any public display",
                null=True,
                verbose_name="End date",
            ),
        ),
        migrations.AlterField(
            model_name="productserviceprice",
            name="price",
            field=models.DecimalField(
                decimal_places=0,
                help_text="Required. Pretax selling price in Japanese yen. Max digits - 10",
                max_digits=10,
                validators=[django.core.validators.MinValueValidator(Decimal("0.01"))],
                verbose_name="Price",
            ),
        ),
    ]
