# Generated by Django 4.2.1 on 2023-10-26 13:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("wagtailcore", "0091_alter_page_title"),
        ("products", "0009_productserviceprice_is_limited_sale_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="LearningExperience",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    models.DateTimeField(auto_now_add=True, verbose_name="created"),
                ),
                (
                    "modified",
                    models.DateTimeField(auto_now=True, verbose_name="modified"),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Required. Max length 200 characters.",
                        max_length=200,
                        verbose_name="Name",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.AlterField(
            model_name="productservice",
            name="price_summary",
            field=models.CharField(
                editable=False,
                help_text="Autogenerated",
                max_length=100,
                verbose_name="Current Price(s) (￥)",
            ),
        ),
        migrations.CreateModel(
            name="LearningExperienceDetailPage",
            fields=[
                (
                    "page_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="wagtailcore.page",
                    ),
                ),
                (
                    "display_title",
                    models.CharField(
                        help_text="Required. Max length 100 characters, 45 or less is ideal",
                        max_length=100,
                        verbose_name="Display Title",
                    ),
                ),
                (
                    "learning_experience",
                    models.OneToOneField(
                        help_text="The associated learning experience",
                        on_delete=django.db.models.deletion.PROTECT,
                        to="products.learningexperience",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
            bases=("wagtailcore.page",),
        ),
        migrations.AddField(
            model_name="learningexperience",
            name="product_service",
            field=models.ForeignKey(
                help_text="Required.",
                on_delete=django.db.models.deletion.PROTECT,
                related_name="learningexperiences",
                to="products.productservice",
            ),
        ),
    ]
