# Generated by Django 4.2.1 on 2023-10-30 17:29

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import wagtail.fields


class Migration(migrations.Migration):
    dependencies = [
        ("wagtailimages", "0025_alter_image_file_alter_rendition_file"),
        ("products", "0011_learningexperiencelistpage"),
    ]

    operations = [
        migrations.AddField(
            model_name="learningexperience",
            name="end_date",
            field=models.DateField(
                default=django.utils.timezone.now,
                help_text="Required.",
                verbose_name="End Date",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="learningexperience",
            name="start_date",
            field=models.DateField(
                default=django.utils.timezone.now,
                help_text="Required.",
                verbose_name="Start Date",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="learningexperiencedetailpage",
            name="header_image",
            field=models.ForeignKey(
                help_text="Image size: 2048px x 1280px. Please optimize image size before uploading.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="wagtailimages.image",
            ),
        ),
        migrations.AddField(
            model_name="learningexperiencedetailpage",
            name="will_do",
            field=wagtail.fields.RichTextField(
                default="put something in here",
                help_text="Required. Include how this helps language learning",
                verbose_name="What you will do",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="learningexperience",
            name="product_service",
            field=models.ForeignKey(
                help_text="Required.",
                limit_choices_to={"ptype": "experience"},
                on_delete=django.db.models.deletion.PROTECT,
                related_name="learningexperiences",
                to="products.productservice",
            ),
        ),
    ]
