# Generated by Django 4.2.1 on 2023-10-31 04:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0012_learningexperience_end_date_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="learningexperience",
            name="max_people",
            field=models.PositiveSmallIntegerField(
                default=0, help_text="Required.", verbose_name="Max People"
            ),
        ),
        migrations.AddField(
            model_name="learningexperience",
            name="total_attended",
            field=models.PositiveSmallIntegerField(
                default=0, help_text="Required.", verbose_name="Total People"
            ),
        ),
        migrations.AddField(
            model_name="learningexperience",
            name="total_new",
            field=models.PositiveSmallIntegerField(
                default=0, help_text="Required.", verbose_name="New people"
            ),
        ),
    ]
