# Generated by Django 4.2.1 on 2023-10-31 04:42

from decimal import Decimal
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0013_learningexperience_max_people_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="learningexperience",
            name="total_profit",
            field=models.DecimalField(
                decimal_places=0,
                default=Decimal("0"),
                help_text="Required. Basic, revenue - total costs including teacher time.",
                max_digits=10,
                validators=[django.core.validators.MinValueValidator(Decimal("0"))],
                verbose_name="Total Profit",
            ),
        ),
    ]
