# Generated by Django 4.2.1 on 2023-10-31 10:21

from decimal import Decimal
import django.core.validators
from django.db import migrations, models
import streams.customblocks
import wagtail.blocks
import wagtail.fields


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0014_learningexperience_total_profit"),
    ]

    operations = [
        migrations.AddField(
            model_name="learningexperiencedetailpage",
            name="past_photos",
            field=wagtail.fields.StreamField(
                [
                    (
                        "simple_image_block",
                        wagtail.blocks.StructBlock(
                            [
                                (
                                    "image",
                                    streams.customblocks.CustomImageChooserBlock(
                                        help_text="Required. Image size: 2048px x 1280px (16/10 ratio)",
                                        required=True,
                                    ),
                                ),
                                (
                                    "caption",
                                    wagtail.blocks.CharBlock(
                                        help_text="Optional. Caption, max length = 200",
                                        max_length=200,
                                        required=False,
                                    ),
                                ),
                            ]
                        ),
                    )
                ],
                null=True,
                use_json_field=True,
            ),
        ),
        migrations.AlterField(
            model_name="learningexperience",
            name="total_profit",
            field=models.DecimalField(
                decimal_places=0,
                default=Decimal("0"),
                help_text="Required. Basic, revenue - total costs including teacher time.",
                max_digits=10,
                validators=[django.core.validators.MinValueValidator(Decimal("0"))],
                verbose_name="Total Profit (￥)",
            ),
        ),
    ]
