# Generated by Django 4.2.1 on 2023-11-06 09:43

from django.db import migrations, models
import django.db.models.deletion
import modelcluster.fields
import streams.customblocks
import wagtail.blocks
import wagtail.fields


class Migration(migrations.Migration):
    dependencies = [
        ("staff", "0008_staffdetailpage_intro"),
        ("products", "0015_learningexperiencedetailpage_past_photos_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="learningexperiencedetailpage",
            name="details",
            field=wagtail.fields.StreamField(
                [
                    (
                        "limited_rich_text_block",
                        streams.customblocks.CustomLimitedRichTextBlock(),
                    ),
                    (
                        "schedule_block",
                        wagtail.blocks.StructBlock(
                            [
                                (
                                    "title",
                                    wagtail.blocks.CharBlock(
                                        help_text="A short title for the schedule. Max 50 chars",
                                        max_length=50,
                                    ),
                                ),
                                (
                                    "intro",
                                    wagtail.blocks.TextBlock(
                                        help_text="Not required. Intro to schedule below",
                                        required=False,
                                    ),
                                ),
                                (
                                    "schedule",
                                    wagtail.blocks.ListBlock(
                                        wagtail.blocks.StructBlock(
                                            [
                                                (
                                                    "date",
                                                    wagtail.blocks.DateBlock(
                                                        help_text="Not Required. Only needed for experience that have multiple sessions",
                                                        required=False,
                                                    ),
                                                ),
                                                (
                                                    "time",
                                                    wagtail.blocks.TimeBlock(
                                                        help_text="Required",
                                                        required=True,
                                                    ),
                                                ),
                                                (
                                                    "detail",
                                                    wagtail.blocks.TextBlock(
                                                        help_text="Required. Max length 500",
                                                        max_length=500,
                                                    ),
                                                ),
                                            ]
                                        )
                                    ),
                                ),
                            ]
                        ),
                    ),
                ],
                null=True,
                use_json_field=True,
            ),
        ),
        migrations.CreateModel(
            name="ExperiencePageStaff",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "sort_order",
                    models.IntegerField(blank=True, editable=False, null=True),
                ),
                (
                    "page",
                    modelcluster.fields.ParentalKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="staff_members",
                        to="products.learningexperiencedetailpage",
                    ),
                ),
                (
                    "staff",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="staff.staffdetailpage",
                    ),
                ),
            ],
            options={
                "ordering": ["sort_order"],
                "abstract": False,
            },
        ),
    ]
