# Generated by Django 4.2.1 on 2023-11-08 13:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0020_learningexperiencedetailpage_end_date_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="learningexperiencedetailpage",
            name="display_tagline",
            field=models.CharField(
                default="A catchy, attractive tagline to give more information and sell the experienc",
                help_text="Required. Max length 160 char. A catchy, attractive tagline to give more information and sell the experience",
                max_length=160,
                verbose_name="Disply Tagline",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="learningexperiencedetailpage",
            name="end_date",
            field=models.DateField(
                blank=True,
                help_text="Read only field that gets value from 'learning_experience'",
                verbose_name="End Date",
            ),
        ),
    ]
