# Generated by Django 4.2.1 on 2023-11-10 11:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("taxes", "0002_alter_tax_options"),
        ("products", "0021_learningexperiencedetailpage_display_tagline_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="productservice",
            name="tax_rate",
            field=models.ForeignKey(
                default=1,
                help_text="Required. Must set correctly.",
                on_delete=django.db.models.deletion.PROTECT,
                related_name="product_services",
                to="taxes.tax",
            ),
            preserve_default=False,
        ),
    ]
