# Generated by Django 4.2.1 on 2023-11-13 06:50

from decimal import Decimal
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0023_productserviceprice_display_name_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="productserviceprice",
            name="before_sale_price",
            field=models.DecimalField(
                blank=True,
                decimal_places=0,
                help_text="NOT Required. Only enter this price for sales prices. It will show up with line through on any front end display",
                max_digits=10,
                null=True,
                validators=[django.core.validators.MinValueValidator(Decimal("0"))],
                verbose_name="Before Sale Pretax Price",
            ),
        ),
    ]
