# Generated by Django 4.2.1 on 2023-11-13 15:10

from decimal import Decimal
import django.core.validators
from django.db import migrations, models
import streams.customblocks
import wagtail.blocks
import wagtail.fields


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0024_productserviceprice_before_sale_price"),
    ]

    operations = [
        migrations.AddField(
            model_name="learningexperiencelistpage",
            name="display_tagline",
            field=models.CharField(
                default="Please add tagline",
                help_text="Required. Max length 160 char. A catchy, attractive tagline to give more information and sell the experiences",
                max_length=160,
                verbose_name="Disply Tagline",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="learningexperiencelistpage",
            name="experiences_gallery",
            field=wagtail.fields.StreamField(
                [
                    (
                        "simple_image_block",
                        wagtail.blocks.StructBlock(
                            [
                                (
                                    "image",
                                    streams.customblocks.CustomImageChooserBlock(
                                        help_text="Required. Image size: 2048px x 1280px (16/10 ratio)",
                                        required=True,
                                    ),
                                ),
                                (
                                    "caption",
                                    wagtail.blocks.CharBlock(
                                        help_text="Optional. Caption, max length = 200",
                                        max_length=200,
                                        required=False,
                                    ),
                                ),
                            ]
                        ),
                    )
                ],
                null=True,
                use_json_field=True,
            ),
        ),
        migrations.AlterField(
            model_name="productserviceprice",
            name="before_sale_price",
            field=models.DecimalField(
                blank=True,
                decimal_places=0,
                help_text="NOT Required. Only enter this price for 'is_limited_sale' prices. It will show up with line through on any front end display to indicate that price has been cut for the limited time",
                max_digits=10,
                null=True,
                validators=[django.core.validators.MinValueValidator(Decimal("0"))],
                verbose_name="Before Sale Pretax Price",
            ),
        ),
    ]
