# Generated by Django 4.2.1 on 2023-11-14 10:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0026_learningexperiencelistpage_intro"),
    ]

    operations = [
        migrations.AddField(
            model_name="productservice",
            name="class_delivery",
            field=models.CharField(
                choices=[
                    ("na", "N/a"),
                    ("online", "Online,オンライン"),
                    ("inperson", "In person,??"),
                    ("hybrid", "Hybrid,??"),
                    ("online-async", "Online Async,??"),
                ],
                default="na",
                help_text="Class field only. How the class is delivered",
                verbose_name="Class Delivery Method",
            ),
        ),
        migrations.AddField(
            model_name="productservice",
            name="class_num",
            field=models.CharField(
                choices=[
                    ("na", "N/a"),
                    ("one-to-one", "OneToOne,マンツーマン"),
                    ("group", "Group,グループ"),
                ],
                default="na",
                help_text="Class field only. Class is one-to-one or group",
                verbose_name="Class People Number",
            ),
        ),
        migrations.AddField(
            model_name="productservice",
            name="class_type",
            field=models.CharField(
                choices=[
                    ("na", "N/a"),
                    ("private", "Private,??"),
                    ("controlled", "Company Controlled"),
                ],
                default="na",
                help_text="Class field only. Class composition is controlled privately or by Xlingual",
                verbose_name="Class Type",
            ),
        ),
        migrations.AlterField(
            model_name="productservice",
            name="name",
            field=models.CharField(
                help_text="Required. Max length 200 characters. English.",
                max_length=200,
                verbose_name="Name",
            ),
        ),
        migrations.AlterField(
            model_name="productservice",
            name="slug",
            field=models.SlugField(
                editable=False,
                help_text="Autogenerated slug. Base slug for product model and any product display models",
                max_length=100,
                unique=True,
                verbose_name="Slug",
            ),
        ),
    ]
