# Generated by Django 4.2.1 on 2023-11-14 15:57

from django.db import migrations, models
import django.db.models.deletion
import wagtail.fields
import wagtail_headless_preview.models


class Migration(migrations.Migration):
    dependencies = [
        #("wagtailcore", "0091_alter_page_title"),
        ("products", "0027_productservice_class_delivery_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="ClassPricesListPage",
            fields=[
                (
                    "page_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="wagtailcore.page",
                    ),
                ),
                (
                    "display_title",
                    models.CharField(
                        help_text="Required. Max length 100 characters, 45 or less is ideal",
                        max_length=100,
                        verbose_name="Display Title",
                    ),
                ),
                (
                    "display_tagline",
                    models.CharField(
                        help_text="Required. Max length 160 char. A catchy, attractive tagline to give more information and sell the classes",
                        max_length=160,
                        verbose_name="Disply Tagline",
                    ),
                ),
                (
                    "intro",
                    wagtail.fields.RichTextField(
                        help_text="Required. For the concepts surrounding Xlingual classes",
                        verbose_name="Introduction",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
            bases=(wagtail_headless_preview.models.HeadlessMixin, "wagtailcore.page"),
        ),
    ]
