# Generated by Django 4.2.1 on 2023-11-15 12:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0029_classpricesdetailpage"),
    ]

    operations = [
        migrations.AddField(
            model_name="productservice",
            name="class_quantity",
            field=models.PositiveSmallIntegerField(
                default=4,
                help_text="Required. Number classes per unit",
                verbose_name="Class Quantity/Unit",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="productservice",
            name="class_unit",
            field=models.CharField(
                choices=[
                    ("na", "N/a"),
                    ("week", "Week,週"),
                    ("month", "Month,月"),
                    ("year", "Year,年"),
                    ("payment", "Payment,支払"),
                ],
                default="na",
                help_text="Required. Unit by which quantity is measured. Example. Month or Payment",
                verbose_name="Class Unit",
            ),
        ),
        migrations.AlterField(
            model_name="productservice",
            name="class_type",
            field=models.CharField(
                choices=[
                    ("na", "N/a"),
                    ("private", "Private,プライベート"),
                    ("controlled", "Company Controlled,一般"),
                ],
                default="na",
                help_text="Class field only. Class composition is controlled privately or by Xlingual",
                verbose_name="Class Type",
            ),
        ),
    ]
