# Generated by Django 4.2.1 on 2023-11-16 10:43

from django.db import migrations, models
import wagtail.fields


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0031_alter_productservice_class_quantity"),
    ]

    operations = [
        migrations.AddField(
            model_name="classpriceslistpage",
            name="private_intro",
            field=wagtail.fields.RichTextField(
                default="Add please",
                help_text="Required. For the concepts surrounding Xlingual private classes. Not too long please",
                verbose_name="Private Classes Introduction",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="classpriceslistpage",
            name="private_tagline",
            field=models.CharField(
                default="Add please",
                help_text="Required. Max length 160 char. A catchy, attractive tagline to give more information and sell the classes",
                max_length=160,
                verbose_name="Private Classes Tagline",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="classpriceslistpage",
            name="private_title",
            field=models.CharField(
                default="Add please",
                help_text="Required. Max length 100 characters, 45 or less is ideal",
                max_length=100,
                verbose_name="Private Classes Title",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="classpriceslistpage",
            name="regular_intro",
            field=wagtail.fields.RichTextField(
                default=1,
                help_text="Required. For the concepts surrounding Xlingual private classes. Not too long please",
                verbose_name="Regular Classes Introduction",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="classpriceslistpage",
            name="regular_tagline",
            field=models.CharField(
                default="Add please",
                help_text="Required. Max length 160 char. A catchy, attractive tagline to give more information and sell the classes",
                max_length=160,
                verbose_name="Regular Classes Tagline",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="classpriceslistpage",
            name="regular_title",
            field=models.CharField(
                default="Add please",
                help_text="Required. Max length 100 characters, 45 or less is ideal",
                max_length=100,
                verbose_name="Regular Classes Title",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="productservice",
            name="class_type",
            field=models.CharField(
                choices=[
                    ("na", "N/a"),
                    ("private", "Private,プライベート"),
                    ("regular", "Regular,一般"),
                ],
                default="na",
                help_text="Class field only. Class composition is controlled privately or by Xlingual",
                verbose_name="Class Type",
            ),
        ),
    ]
