# Generated by Django 4.2.1 on 2023-11-21 06:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0033_remove_productservice_class_delivery_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="productservice",
            name="is_native",
            field=models.BooleanField(
                help_text="NOT Required. Is run by a native language speaker if applicable?",
                null=True,
                verbose_name="Is Native",
            ),
        ),
        migrations.AlterField(
            model_name="productservice",
            name="bookable_online",
            field=models.BooleanField(
                help_text="NOT Required. Can be booked online if applicable",
                null=True,
                verbose_name="Bookable online",
            ),
        ),
        migrations.AlterField(
            model_name="productservice",
            name="has_onlinenotes",
            field=models.BooleanField(
                help_text="NOT Required. Has onlinenotes if applicable ?",
                null=True,
                verbose_name="Has Online Notes",
            ),
        ),
        migrations.AlterField(
            model_name="productservice",
            name="is_inperson",
            field=models.BooleanField(
                help_text="NOT Required. Is able to be taken in person if applicable?",
                null=True,
                verbose_name="Is Inperson",
            ),
        ),
        migrations.AlterField(
            model_name="productservice",
            name="is_online",
            field=models.BooleanField(
                help_text="NOT Required. Is able to be taken online if applicable?",
                null=True,
                verbose_name="Is Online",
            ),
        ),
        migrations.AlterField(
            model_name="productservice",
            name="length",
            field=models.PositiveSmallIntegerField(
                blank=True,
                help_text="NOT Required. Length of class or experience if applicable. Example. Number of Minutes or number of words",
                null=True,
                verbose_name="Length",
            ),
        ),
        migrations.AlterField(
            model_name="productservice",
            name="max_num",
            field=models.PositiveSmallIntegerField(
                blank=True,
                help_text="NOT Required. Max Number of people if applicable",
                null=True,
                verbose_name="Max Num People",
            ),
        ),
        migrations.AlterField(
            model_name="productservice",
            name="min_num",
            field=models.PositiveSmallIntegerField(
                blank=True,
                help_text="NOT Required. Min Number of people if applicable",
                null=True,
                verbose_name="Min Num People",
            ),
        ),
        migrations.AlterField(
            model_name="productservice",
            name="quantity",
            field=models.PositiveSmallIntegerField(
                blank=True,
                help_text="NOT Required. Quantity if applicable (Per Unit) ",
                null=True,
                verbose_name="Quantity",
            ),
        ),
    ]
