# Generated by Django 4.2.1 on 2023-12-30 04:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0035_remove_classpricesdetailpage_sales_point1_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="productservice",
            name="class_type",
            field=models.CharField(
                choices=[
                    ("na", "N/a"),
                    ("private", "Private,プライベート"),
                    ("regular", "Regular,一般"),
                ],
                default="na",
                help_text="Class field only. Class composition is controlled privately or by Xlingual",
                max_length=20,
                verbose_name="Class Type",
            ),
        ),
        migrations.AlterField(
            model_name="productservice",
            name="group_or_one",
            field=models.CharField(
                choices=[
                    ("na", "N/a"),
                    ("one-to-one", "OneToOne,マンツーマン"),
                    ("group", "Group,グループ"),
                ],
                default="na",
                help_text="One-to-one or group if applicable",
                max_length=20,
                verbose_name="Group or 1-to-1",
            ),
        ),
        migrations.AlterField(
            model_name="productservice",
            name="length_unit",
            field=models.CharField(
                choices=[
                    ("na", "N/a"),
                    ("minutes", "Minutes,分"),
                    ("words", "Words,単語"),
                ],
                default="na",
                help_text="Required. Unit by which length is measured. Example. Minutes or words",
                max_length=20,
                verbose_name="Class Length Unit",
            ),
        ),
        migrations.AlterField(
            model_name="productservice",
            name="ptype",
            field=models.CharField(
                choices=[
                    ("class", "Class"),
                    ("experience", "Learning Experience"),
                    ("book", "Book"),
                    ("joiningfee", "Joining Fee"),
                ],
                help_text="Required",
                max_length=20,
                verbose_name="Product or Service Type",
            ),
        ),
        migrations.AlterField(
            model_name="productservice",
            name="quantity_unit",
            field=models.CharField(
                choices=[
                    ("na", "N/a"),
                    ("week", "Week,週"),
                    ("month", "Month,月"),
                    ("year", "Year,年"),
                    ("payment", "Payment,支払"),
                ],
                default="na",
                help_text="Required. Unit by which quantity is measured. Example. Month or Payment",
                max_length=20,
                verbose_name="Quantity Unit",
            ),
        ),
        migrations.AlterField(
            model_name="productservice",
            name="service_or_product",
            field=models.CharField(
                choices=[("service", "Service"), ("product", "Product")],
                help_text="Required",
                max_length=20,
                verbose_name="Service or Product",
            ),
        ),
    ]
