# Generated by Django 4.2.1 on 2024-02-20 11:42

from django.db import migrations, models
import wagtail.fields


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0036_alter_productservice_class_type_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="learningexperiencelistpage",
            name="display_tagline",
        ),
        migrations.AddField(
            model_name="learningexperiencelistpage",
            name="gallery_en_title",
            field=models.CharField(
                default="Please add",
                help_text="Required. Max length 25, 15 or less is ideal",
                max_length=25,
                verbose_name="LE - Gallery English title",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="learningexperiencelistpage",
            name="gallery_jp_title",
            field=models.CharField(
                default="Please add",
                help_text="Required. Max length 20 characters, 15 or less is ideal",
                max_length=20,
                verbose_name="LE - Japanese Title",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="learningexperiencelistpage",
            name="upcoming_en_title",
            field=models.CharField(
                default="Please add",
                help_text="Required. Max length 25, 15 or less is ideal",
                max_length=25,
                verbose_name="LE - Upcoming English title",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="learningexperiencelistpage",
            name="upcoming_jp_title",
            field=models.CharField(
                default="Please add",
                help_text="Required. Max length 20 characters, 15 or less is ideal",
                max_length=20,
                verbose_name="Mission - Japanese Title",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="learningexperiencelistpage",
            name="display_title",
            field=models.CharField(
                help_text="Required. Max length 15 characters. Japanese",
                max_length=15,
                verbose_name="Display Title",
            ),
        ),
        migrations.AlterField(
            model_name="learningexperiencelistpage",
            name="intro",
            field=wagtail.fields.RichTextField(
                help_text="Required. For the concepts surrounding learning experiences",
                verbose_name="LE - Intro",
            ),
        ),
    ]
