# Generated by Django 4.2.1 on 2024-03-25 06:15

from django.db import migrations, models
import django.db.models.deletion
import modelcluster.fields
import wagtail.fields


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0038_learningexperiencelistpage_intro_en_title_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="classpriceslistpage",
            name="display_tagline",
        ),
        migrations.RemoveField(
            model_name="classpriceslistpage",
            name="intro",
        ),
        migrations.RemoveField(
            model_name="classpriceslistpage",
            name="private_tagline",
        ),
        migrations.RemoveField(
            model_name="classpriceslistpage",
            name="private_title",
        ),
        migrations.RemoveField(
            model_name="classpriceslistpage",
            name="regular_tagline",
        ),
        migrations.RemoveField(
            model_name="classpriceslistpage",
            name="regular_title",
        ),
        migrations.AddField(
            model_name="classpriceslistpage",
            name="private_en_title",
            field=models.CharField(
                default="Please add",
                help_text="Required. Max length 25, 15 or less is ideal",
                max_length=25,
                verbose_name="Private Plans - English Title",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="classpriceslistpage",
            name="private_jp_title",
            field=models.CharField(
                default="Please add",
                help_text="Required. Max length 20 characters, 15 or less is ideal",
                max_length=20,
                verbose_name="Private Plans - Japanese Title",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="classpriceslistpage",
            name="regular_en_title",
            field=models.CharField(
                default="Please add",
                help_text="Required. Max length 25, 15 or less is ideal",
                max_length=25,
                verbose_name="Regular Plans - English Title",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="classpriceslistpage",
            name="regular_jp_title",
            field=models.CharField(
                default="Please add",
                help_text="Required. Max length 20 characters, 15 or less is ideal",
                max_length=20,
                verbose_name="Regular Plans - Japanese Title",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="classpriceslistpage",
            name="display_title",
            field=models.CharField(
                help_text="Required. Max length 15 characters, Japanese",
                max_length=15,
                verbose_name="Price Plans display title",
            ),
        ),
        migrations.AlterField(
            model_name="classpriceslistpage",
            name="private_intro",
            field=wagtail.fields.RichTextField(
                help_text="Required. Introduce the benifits of Xlingual private plans",
                verbose_name="Private Plans - Intro",
            ),
        ),
        migrations.AlterField(
            model_name="classpriceslistpage",
            name="regular_intro",
            field=wagtail.fields.RichTextField(
                help_text="Required. Introduce the benifits of Xlingual private plans",
                verbose_name="Regular Plans - Intro",
            ),
        ),
        migrations.CreateModel(
            name="PrivatePricePlans",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "sort_order",
                    models.IntegerField(blank=True, editable=False, null=True),
                ),
                (
                    "page",
                    modelcluster.fields.ParentalKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="private_price_plans",
                        to="products.classpriceslistpage",
                    ),
                ),
                (
                    "price_plan",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="products.classpricesdetailpage",
                    ),
                ),
            ],
            options={
                "ordering": ["sort_order"],
                "abstract": False,
            },
        ),
    ]
