# Generated by Django 4.2.1 on 2024-03-25 06:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0039_remove_classpriceslistpage_display_tagline_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="privatepriceplans",
            name="price_plan",
            field=models.ForeignKey(
                limit_choices_to={"class_service__class_type": "private"},
                on_delete=django.db.models.deletion.CASCADE,
                to="products.classpricesdetailpage",
            ),
        ),
    ]
