# Generated by Django 4.2.1 on 2024-03-26 15:41

from django.db import migrations, models
import django.db.models.deletion
import modelcluster.fields


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0040_alter_privatepriceplans_price_plan"),
    ]

    operations = [
        migrations.CreateModel(
            name="RegularPricePlans",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "sort_order",
                    models.IntegerField(blank=True, editable=False, null=True),
                ),
                (
                    "page",
                    modelcluster.fields.ParentalKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="regular_price_plans",
                        to="products.classpriceslistpage",
                    ),
                ),
                (
                    "price_plan",
                    models.ForeignKey(
                        limit_choices_to={"class_service__class_type": "regular"},
                        on_delete=django.db.models.deletion.CASCADE,
                        to="products.classpricesdetailpage",
                    ),
                ),
            ],
            options={
                "ordering": ["sort_order"],
                "abstract": False,
            },
        ),
    ]
