# Generated by Django 4.2.1 on 2025-09-05 09:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0042_alter_classpricesdetailpage_class_intro"),
    ]

    operations = [
        migrations.AlterField(
            model_name="learningexperiencelistpage",
            name="gallery_en_title",
            field=models.CharField(
                help_text="Required. Max length 35",
                max_length=35,
                verbose_name="LE - Gallery English title",
            ),
        ),
        migrations.AlterField(
            model_name="learningexperiencelistpage",
            name="gallery_jp_title",
            field=models.CharField(
                help_text="Required. Max length 30",
                max_length=30,
                verbose_name="LE - Japanese Title",
            ),
        ),
        migrations.AlterField(
            model_name="learningexperiencelistpage",
            name="intro_jp_title",
            field=models.CharField(
                help_text="Required. Max length 20 characters, 15 or less is ideal",
                max_length=30,
                verbose_name="Intro - Japanese Title",
            ),
        ),
        migrations.AlterField(
            model_name="learningexperiencelistpage",
            name="upcoming_en_title",
            field=models.CharField(
                help_text="Required. Max length 35",
                max_length=35,
                verbose_name="LE - Upcoming English title",
            ),
        ),
        migrations.AlterField(
            model_name="learningexperiencelistpage",
            name="upcoming_jp_title",
            field=models.CharField(
                help_text="Required. Max length 30",
                max_length=30,
                verbose_name="Mission - Japanese Title",
            ),
        ),
    ]
